package com.arcsoft.commander.domain.matrix;

// Generated 2014-7-24 11:19:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.arcsoft.commander.domain.server.ServerGroup;

/**
 * Matrix generated by hbm2java
 */
public class Matrix implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6520083583294270606L;
	private Integer id;
	private String ip;
	private String name;
	private String remarks;
	private Set<MatrixSetting> matrixSettings = new HashSet<MatrixSetting>(0);

	private ServerGroup serverGroup;
	private Integer port;
	
	public Matrix() {
	}

	public Matrix(String ip) {
		this.ip = ip;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	
	/**
	 * @return the matrixSettings
	 */
	public Set<MatrixSetting> getMatrixSettings() {
		return matrixSettings;
	}

	
	/**
	 * @param matrixSettings the matrixSettings to set
	 */
	public void setMatrixSettings(Set<MatrixSetting> matrixSettings) {
		this.matrixSettings = matrixSettings;
	}

	
	/**
	 * @return the serverGroup
	 */
	public ServerGroup getServerGroup() {
		return serverGroup;
	}

	
	/**
	 * @param serverGroup the serverGroup to set
	 */
	public void setServerGroup(ServerGroup serverGroup) {
		this.serverGroup = serverGroup;
	}

	
	/**
	 * @return the port
	 */
	public Integer getPort() {
		return port;
	}

	
	/**
	 * @param port the port to set
	 */
	public void setPort(Integer port) {
		this.port = port;
	}

}
