package com.arcsoft.commander.domain.matrix;

import com.arcsoft.commander.domain.server.Server;

// Generated 2014-7-24 11:19:16 by Hibernate Tools 3.4.0.CR1

/**
 * MatrixSetting generated by hbm2java
 */
public class MatrixSetting implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4112444504217003515L;
	private Integer id;
	private Server server;
	private Matrix matrix;
	private Integer sdiPort;
	private Integer matrixOut;
	private Integer matrixMasterIn;
	private Integer matrixSlaveIn;
	private String remarks;

	public MatrixSetting() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	

	public Matrix getMatrix() {
		return this.matrix;
	}

	public void setMatrix(Matrix matrix) {
		this.matrix = matrix;
	}

	public Integer getSdiPort() {
		return this.sdiPort;
	}

	public void setSdiPort(Integer sdiPort) {
		this.sdiPort = sdiPort;
	}

	public Integer getMatrixOut() {
		return this.matrixOut;
	}

	public void setMatrixOut(Integer matrixOut) {
		this.matrixOut = matrixOut;
	}

	public Integer getMatrixMasterIn() {
		return this.matrixMasterIn;
	}

	public void setMatrixMasterIn(Integer matrixMasterIn) {
		this.matrixMasterIn = matrixMasterIn;
	}

	public Integer getMatrixSlaveIn() {
		return this.matrixSlaveIn;
	}

	public void setMatrixSlaveIn(Integer matrixSlaveIn) {
		this.matrixSlaveIn = matrixSlaveIn;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	
	/**
	 * @return the server
	 */
	public Server getServer() {
		return server;
	}

	
	/**
	 * @param server the server to set
	 */
	public void setServer(Server server) {
		this.server = server;
	}

}
