package com.arcsoft.commander.domain.security;

// Generated 2014-6-6 10:22:29 by Hibernate Tools 3.4.0.CR1

/**
 * RoleResource generated by hbm2java
 */
public class RoleOperator implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Role role;
	private int operatorId;

	public RoleOperator() {
	}

	public RoleOperator(Role role, int operatorId) {
		this.role = role;
		this.operatorId = operatorId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public int getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(int operatorId) {
		this.operatorId = operatorId;
	}


}
