/*JS class*/
var CLASS_HIDE ="Hide";
var CLASS_CHANGED_TEXT		="ChangedText";
var CLASS_UNDERLINE_TRIGGER = "UnderLineTab_Trigger";
var CLASS_UNDERLINE_ACTIVE = "UnderLineTab_Active";
var CLASS_ICON_ARROW_RIGHT ="ICON_ArrowRight";
var CLASS_ICON_ARROW_DOWN ="ICON_ArrowDown";
var CLASS_COLOR_TRIGGER = "ColorTab_Trigger";
var CLASS_COLOR_ACTIVE = "ColorTab_Active";

/** come from DialogFrame.jsp **/
var ID_BUTTON_OK ="ButtonOK";
var JS_BUTTON_OK ="#ButtonOK";
var JS_BUTTON_CANCEL ="#ButtonCancel";
var JS_LABEL_OK ="#LabelOK";
var JS_DIALOG_CONTAINER =".DF_Container";
var JS_BUTTON_TRIGGER =".ButtonTrigger";
var JS_DIALOG_TITLE_TEXT =".DF_TitleText";
var JS_DIALOG_HEAD_LINE	=".DF_HeadLine";
var JS_DIALOG_FRAME_TEMPLATE ="#DialogFrameTemplate";

/** jquery Selector **/
var JS_TASK					=".Task";
var JS_NEW_INPUT_TRIGGER	=".NewInputTrigger";
var JS_SUBMIT_TRIGGER		=".SubmitTrigger";
var JS_BACK_TRIGGER			=".BackTrigger";
var JS_SAVE_AS_PROFILE		=".SaveAsProfile";
var JS_NEW_OUTPUT_GROUP_TRIGGER	=".NewOutputGroupTrigger";
var JS_COPY_OUTPUT_GROUP_TRIGGER	=".CopyOutputGroupTrigger";
var JS_STREAM_FLOCK			=".StreamFlock";
var JS_STREAM_INDEX			=".StreamIndex";
var JS_NEW_STREAM_TRIGGER	=".NewStreamTrigger";
var JS_IMPORT_PRESET_TRIGGER	=".ImportPresetTrigger";
var JS_STREAM_ID_GENERATOR	= ".StreamIdGenerator";
var JS_CLOSE_TRIGGER		=".CloseTrigger";
var JS_IMPORT_PROFILE		=".ImportProfileTrigger";
var JS_OUTPUT_GROUP_TAB		=".OutputGroupTab";
var JS_OPEN_FILE_TRIGGER	=".OpenFileTrigger";
var JS_INSERT_MACRO_TRIGGER = ".InsertMacroTrigger";
var JS_INPUT_OPEN_SDP_TRIGGER = ".OpenSDPTrigger";
var JS_INPUT_ESOVERRTP_SETTING = ".ESOverRTPSetting";
var JS_INPUT_INFO			=".InputInfo";
var JS_STREAM				=".Stream";
var JS_SUMMARY_TRIGGER		=".SummaryTrigger";
var JS_SAVE_AS_PRESET		=".SaveAsPreset";
var JS_IMPORT_PRESET		=".ImportPreset";
var JS_VIDEO_FLOCK			=".VideoFlock";
var JS_AUDIO_FLOCK			=".AudioFlock";
var JS_STREAM_FLOCK			=".StreamFlock";
var JS_VIDEO_DESCRIPTION	=".VideoDescription";
var JS_VIDEO_CONTAINER		=".VideoContainer";
var JS_VIDEO_DETAIL			=".VideoDetail";
var JS_ENCODING_POLICY = ".EncodingPolicy";
var JS_TWO_PASS_OPTION = ".TwoPassOption";
var JS_ENCODING_POLICY_COMMENT = ".EncodingPolicyComment";
var JS_AUDIO_DESCRIPTION	=".AudioDescription";
var JS_INPUT				=".Input";
var JS_INPUT_NOTE			=".InputNote";
var JS_INPUT_FLOCK			=".InputFlock";
var JS_DELETE_INPUT_TRIGGET	=".DeleteInputTrigger";
var JS_INPUT_OPTION			=".InputOption";
var JS_INPUT_INDEX			=".InputIndex";
var JS_INPUT_MEDIA_INFO		=".InputMediaInfo";
var JS_INPUT_PREVIEW_TRIGGER	=".InputPreviewTrigger";
var JS_INPUT_SEPCIAL_OPTION =".InputSepcialOption";
var JS_PROGRAM_EDITOR		= ".ProgramEditor";
var JS_INPUT_EDITOR			=".InputEditor";
var JS_INPUT_EDITOR_TAB		=".InputEditorTab";
var JS_INPUT_EDITOR_PANEL	=".InputEditorPanel";
var JS_VALUE_CHANGER		=".ValueChanger";
var JS_SELECT_BOX_TRIGGER	=".SelectBoxTrigger";
var JS_PREVIEW_MOSAIC_TRIGGER	=".PreviewMosaicTrigger";
var JS_NEW_MOSAIC_TRIGGER	=".NewMosaicTrigger";
var JS_DELETE_MOSAIC_TRIGGER	=".DeleteMosaicTrigger";
var JS_MOSAIC_ITEM_CONTAINER	=".MosaicItemContainer";
var JS_MOSAIC_ITEM			=".MosaicItem";
var JS_MOSAIC_ITEM_INDEX	=".MosaicItemIndex";
var JS_NEW_LOGO_TRIGGER		=".NewLogoTrigger";
var JS_DELETE_LOGO_TRIGGER	=".DeleteLogoTrigger";
var JS_LOGO_ITEM_CONTAINER	=".LogoItemContainer";
var JS_LOGO_ITEM			=".LogoItem";
var JS_LOGO_ITEM_INDEX		=".LogoItemIndex";
var JS_SELECT_LOGO_TRIGGER = ".SelectLogoTrigger";
var JS_PREVIEW_TRIM_TRIGGER	=".PreviewTrimTrigger";
var JS_PREVIEW_CLIP_TRIGGER	=".PreviewClipTrigger";
var JS_EDITOR_MOSAIC		=".EditorMosaic";
var JS_EDITOR_TRIM			=".EditorTrim";
var JS_EDITOR_PADDING_IMAGE =".EditorPaddingImage";
var JS_EDITOR_AUDIO_PROCESS =".EditorAudioProcess";
var JS_EDITOR_TIMECLIPPING	=".EditorTimeClipping";
var JS_ADVERTISEMENT	=".Advertisement";
var JS_EDITOR_LOGO_INSERTER =".EditorLogoInserter";
var JS_EDITOR_SUBTITLE =".EditorSubtitle";
var JS_SUBTITLE_SUPPORTED = ".SubtitleSupported";
var JS_NEW_SUBTITLE_TRIGGER		=".NewSubtitleTrigger";
var JS_SELECT_SUBTITLE_TRIGGER  =".SelectSubtitleTrigger";
var JS_DELETE_SUBTITLE_TRIGGER	=".DeleteSubtitleTrigger";
var JS_SUBTITLE_ITEM_INDEX	=".SubtitleItemIndex";
var JS_SUBTITLE_ITEM		= ".SubtitleItem";
var JS_SUBTITLE_ITEM_CONTAINER = ".SubtitleItemContainer";
var JS_VIDEO_PROCESSING	=".VideoProcessing";
var JS_NEW_CLIP_TRIGGER		= ".NewClipTrigger";
var JS_DELETE_CLIP_TRIGGER	= ".DeleteClipTrigger";
var JS_CLIP_CONTAINER		= ".ClipContainer";
var JS_CLIP_START_TRIGGER	= ".ClipStartTrigger";
var JS_CLIP_END_TRIGGER		= ".ClipEndTrigger";
var JS_JUMP_CLIP_START_TRIGGER	= ".JumpClipStartTrigger";
var JS_JUMP_CLIP_END_TRIGGER	= ".JumpClipEndTrigger";
var JS_CLIP_INDEX			= ".ClipIndex";
var JS_PLAYER_CONTAINER 	=".TMPlayerContainer";
var JS_PREVIEW_PLAYER		="#ArcSoft_TMPlayer";
var JS_PROTOCOL_TRIGGER		=".ProtocolTrigger";
var JS_TIMESLICE_GROUP		=".TimesliceGroup";
var JS_TIMESLICE			=".Timeslice";
var JS_OUTPUT_GROUP			=".OutputGroup";
var JS_OUTPUT_GROUP_FLOCK	=".OutputGroupFlock";
var JS_DELETE_OUTPUT_GROUP_TRIGGER	=".DeleteOutputGroupTrigger";
var JS_SEGMENTLENGTH_GROUP	=".SegmentLengthGroup";
var JS_SEGMENT_RECORD_LENGTH_ITEM = ".SegmentRecordLengthItem";
var JS_SEGMENT_TYPE_ITEM = ".SegmentTypeItem";
var JS_BYTE_RANGE_MODE_ITEM = ".ByteRangeModeItem"
var JS_PLAYLIST_TYPE_ITEM = ".PlaylistTypeItem";
var JS_PLAYLIST_NAME_MODE_ITEM = ".PlaylistNameModeItem";
var JS_EPG_FILE_ITEM = ".EpgFileItem";
var JS_OPEN_EPG_FILE_TRIGGER = ".OpenEpgFileTrigger";
var JS_TS_ADVANCED_OPTIONS	=".TSAdvancedOptions";
var JS_ES_SETTING = ".ESSetting";
var JS_TS_OVER_RTP_SETTING = ".TSOverRTPSetting";
var JS_DRM_OPTIONS	=".DRMOptions";
var JS_OUTPUT_GROUP_OPTION	=".OutputGroupOption";
var JS_OUTPUT_GROUP_SPECIAL	=".OutputGroupSpecial";
var JS_OUTPUT_PREVIEW_TRIGGER	=".OutputPreviewTrigger";
var JS_OUTPUT				=".Output";
var JS_SUMMARY				=".Summary";
var JS_OUTPUT_FLOCK			=".OutputFlock";
var JS_NEW_OUTPUT_TRIGGER	=".NewOutputTrigger";
var JS_NEW_OUTPUT_BAR		=".NewOutputBar";
var JS_DELETE_OUTPUT_TRIGGER	=".DeleteOutputTrigger";
var JS_EDIT_OUTPUT_TRIGGER	=".EditOutputTrigger";
var JS_OUTPUT_STREAM_EXPAND	=".StreamExpand";
var JS_OUTPUT_INDEX			=".OutputIndex";
var JS_PRESET				=".Preset";
var JS_CATEGORY_LIST_TRIGGER	=".CategoryListTrigger";
var JS_WATCH_FOLDER			=".WatchFolder";
var JS_FILE_FILTER_EXPAND	=".FileFilterExpand";
var JS_RESOLUTION_FILTER_EXPAND = ".ResolutionFilterExpand";
var JS_SCHEDULE				=".Schedule";
var JS_SCHEDULE_TIME_SETTING	=".ScheduleTimeSetting";
var JS_SCHEDULE_START_TIME	=".ScheduleStartTime";
var JS_SCHEDULE_END_TIME	=".ScheduleEndTime";
var JS_RECURRENCE_EXPAND	=".RecurrenceExpand";
var JS_RECURRENCE_PERIOD	=".RecurrencePeriod";
var JS_RECURRENCE_DAILY		=".RecurrenceDaily";
var JS_RECURRENCE_WEEKLY	=".RecurrenceWeekly";
var JS_RECURRENCE_MONTHLY	=".RecurrenceMonthly";
var JS_RECURRENCE_END_TIME	=".RecurrenceEndTime";
var JS_UNSUPPORT = ".Unsupport";
var JS_SUPPORT = ".Support";
var JS_SEEK_TIME_TRIGGER = ".SeekTimeTrigger";
var JS_OUTPUT_GROUP_URI_DISP = ".OutputGroupUriDisp";
var JS_ACTION_TYPE = "#ActionType";
var JS_OPEN_SCRIPT_TRIGGER = ".OpenScriptTrigger";
var JS_CONTAINER_SETTING_DIV = ".ContainerSettingDiv";
var JS_DRM_SETTING_DIV = ".DrmSettingDiv";
var JS_DRM_SETTING_CONTAINER = ".DRMSettingContainer";
var JS_DRM_SETTING = ".DRMSetting";
var JS_PALETTE_TRIGGER = ".PaletteTrigger";

/* license control */
var JS_TASK_PRIORITY_MODULE =".TaskPriorityModule";
var JS_LICENSE_POST_PROCESS = ".LicensePostProcess";
var JS_LICENSE_TRANS_GPU_ID = ".LicenseGpuId";
var JS_LICENSE_TRANS_VIDEO_DECODING = ".LicenseVideoDecoding";
var JS_LICENSE_ENCODING_POLICY = ".LicenseEncodingPolicy";
var JS_LICENSE_FILL_ON_STREAM_LOST = ".LicenseFillOnStreamLost";
var JS_LICENSE_SRC_IP = ".LicenseSrcIp";
var JS_LICENSE_FAILOVER_TIME = ".LicenseFailoverTime";
var JS_LICENSE_ALLOW_PROGRAM_ID_CHANGE = ".LicenseAllowProgramIdChange";
var JS_LICENSE_ENABLE_SUBFOLDER = ".LicenseEnableSubfolder";
var JS_LICENSE_WATCH_FOLDER_SUBTITLE = ".LicenseWatchFolderSubtitle";
var JS_LICENSE_FILE_FILTER = ".LicenseFileFilter";
var JS_LICENSE_SMART_BORDER = ".LicenseSmartBorder";
var JS_LICENSE_VIDEO_CODEC_ID = ".LicenseVideoCodecId";
var JS_LICENSE_VIDEO_PLAY_RATE = ".LicenseVideoPlayRate";
var JS_LICENSE_VIDEO_H263_LEVEL = ".LicenseH263Level";
var JS_VIDEO_ENCODER_INTERLACE_FIELD_1ST_MODE_SHOW = ".LicenseField1stShow";
var JS_LICENSE_GOP_MODE_ID = ".LicenseGopModeId";
var JS_LICENSE_FRAME_RATE_MODE = ".LicenseFrameRateMode";
var JS_LICENSE_FILL_ON_VIDEO_LOST = ".LicenseFillOnVideoLost";
var JS_LICENSE_VIDEO_QUANTIZER = ".LicenseVideoQuantizer";
var JS_LICENSE_LIVE_SETTING = ".LicenseLiveSetting";
var JS_LICENSE_MATERIAL = ".LicenseMaterial";

/** These selector is used in HTML input or select **/
var JS_ID					="input[name='Id']";
var JS_GUID					="input[name='Guid']";
var JS_NAME					="input[name='Name']";
var JS_PAGE_NAME			="input[name='PageName']";
var JS_DESCRIPTION			="input[name='Description']";
var JS_ACTION				="input[name='Action']";
var JS_ENCODING_OPTION		="select[name='TaskEncodingOption']";
var JS_PRIORITY				="select[name='TaskPriority']";
var JS_GPUID				="select[name='TaskGpuId']";
var JS_VIDEO_DECODING		="select[name='TaskVideoDecoding']";
var JS_SCRIPT_URI			="input[name='ScriptUri']";
var JS_FILL_ON_STREAM_LOST = "input[name='FillOnStreamLost']";
var JS_TASK_ACTION			="input[name='taskAction']";
var JS_PROFILE_ACTION		="input[name='profileAction']";
var JS_SUBTITLE_ENABLE ="input[name='SubtitleEnable']";
var JS_SUBTITLE_URI ="input[name='SubtitleUri']";
var JS_SUBTITLE_OPACITY ="input[name='SubtitleOpacity']";
var JS_SUBTITLE_COLOR ="input[name='SubtitleColor']";
var JS_SUBTITLE_FONT_FAMILY ="select[name='SubtitleFontFamily']";
var JS_SUBTITLE_FONT_SIZE ="input[name='SubtitleFontSize']";
var JS_SUBTITLE_ENGLISH_FONT ="select[name='SubtitleEnglishFont']";
var JS_SUBTITLE_ENGLISH_SIZE ="input[name='SubtitleEnglishSize']";
var JS_SUBTITLE_SYNC ="input[name='SubtitleSync']";
var JS_SUBTITLE_VERTICAL_POSITION = "input[name='SubtitleVerticalPosition']";
var JS_SUBTITLE_LEFT = "input[name='SubtitleLeft']";
var JS_SUBTITLE_TOP = "input[name='SubtitleTop']";
var JS_SUBTITLE_WIDTH = "input[name='SubtitleWidth']";
var JS_SUBTITLE_HEIGHT = "input[name='SubtitleHeight']";
var JS_SUBTITLE_POSITION_TYPE = "input[name='SubtitlePositionType']";
var JS_SUBTITLE_FONT_INFO_TYPE = "input[name='SubtitleFontInfoType']";
var JS_INPUT_TYPE			="select[name='InputType']";
var JS_INPUT_BODY			="input[name='InputBody']";
var JS_INPUT_URI			="input[name='InputURI']";
var JS_INPUT_FORMAT			="select[name='InputFormat']";
var JS_INPUT_FAILOVER_TIME	="input[name='FailoverTime']";
var JS_INPUT_FAILOVER_TIME_SECOND	="input[name='FailoverTimeSecond']";
var JS_INPUT_SRC_IP	="select[name='SrcIp']";
var JS_INPUT_SRC_IP_DOWN	="input[name='SrcIpDown']";
var JS_INPUT_VIDEO_RTP_URI	="input[name='VideoRtpUri']";
var JS_INPUT_AUDIO_RTP_URI	="input[name='AudioRtpUri']";
var JS_INPUT_VIDEO_RTCP_URI	="input[name='VideoRtcpUri']";
var JS_INPUT_AUDIO_RTCP_URI	="input[name='AudioRtcpUri']";
var JS_INPUT_SDP_URI	="input[name='SDPURI']";
var JS_INPUT_PORT	="select[name='InputPort']";
var JS_INPUT_PORT_DOWN ="input[name='InputPortDown']";
var JS_INPUT_LIVE_SYNC_MODE ="input[name='InputLiveSyncMode']";
var JS_INPUT_KEY	="input[name='InputKey']";
var JS_INPUT_PROGRAM_ID_DOWN		="input[name='ProgramIdDown']";
var JS_INPUT_AUDIO_TRACK_ID_DOWN	="input[name='AudioTrackIdDown']";
var JS_INPUT_SUBTITLE_ID_DOWN	="input[name='SubtitleIdDown']";
var JS_INPUT_ANGLE_ID_DOWN	="input[name='AngleIdDown']";
var JS_INPUT_AUDIO_CHANNEL_ID_DOWN	="input[name='AudioChannelIdDown']";
var JS_INPUT_PROGRAM_ID		="select[name='ProgramId']";
var JS_INPUT_AUDIO_TRACK_ID	="select[name='AudioTrackId']";
var JS_INPUT_SUBTITLE_ID	="select[name='SubtitleId']";
var JS_INPUT_ANGLE_ID	="select[name='AngleId']";
var JS_INPUT_AUDIO_CHANNEL_ID	="select[name='AudioChannelId']";
var JS_INPUT_4K	="input[name='Input4k']";
var JS_INPUT_PROTOCOL		="select[name='InputProtocol']";
var JS_INPUT_ALLOW_PROGRAM_ID_CHANGE = "input[name='AllowProgramIdChange']";
var JS_INPUT_FILL_TYPE = "select[name='InputFillType']";
var JS_DELAY_OUTPUT_TIME = "input[name='DelayOutputTime']";
var JS_FILL_LOST_TIME = "input[name='FillLostTime']";
var JS_FILL_MODE_LOST = "input[name='FillModeLost']";
var JS_MOSAIC_ENABLE		="input[name='MosaicEnable']";
var JS_MOSAIC_BLUR			="select[name='MosaicBlur']";
var JS_MOSAIC_X				="input[name='MosaicX']";
var JS_MOSAIC_Y				="input[name='MosaicY']";
var JS_MOSAIC_WIDTH			="input[name='MosaicWidth']";
var JS_MOSAIC_HEIGHT		="input[name='MosaicHeight']";
var JS_MOSAIC_ACTIVE_TIME	="input[name='MosaicActiveTime']";
var JS_MOSAIC_START	="input[name='MosaicStart']";
var JS_MOSAIC_END	="input[name='MosaicEnd']";
var JS_MOSAIC_TYPE	="select[name='MosaicType']";
var JS_LOGO_ENABLE			="input[name='LogoEnable']";
var JS_LOGO_URI				="input[name='LogoURI']";
var JS_LOGO_X				="input[name='LogoX']";
var JS_LOGO_Y				="input[name='LogoY']";
var JS_LOGO_OPACITY			="input[name='LogoOpacity']";
var JS_LOGO_RESIZE			="input[name='LogoResize']";
var JS_TRIM_ENABLE			="input[name='TrimEnable']";
var JS_TRIM_X				="input[name='TrimX']";
var JS_TRIM_Y				="input[name='TrimY']";
var JS_TRIM_WIDTH			="input[name='TrimWidth']";
var JS_TRIM_HEIGHT			="input[name='TrimHeight']";
var JS_TIMECLIPPING_ENABLE	="input[name='TimeClippingEnable']";
var JS_TIMECLIPPING_MODE	="input[name='TimeClippingMode']";
var JS_TIMECLIPPING_TRIMMED	="input[name='TimeClippingTrimmed']";
var JS_TIMESLICE_ENABLE		="input[name='TimesliceEnable']";
var JS_TIMESLICE_TRIMMED	="input[name='TimesliceTrimmed']";
var JS_TIMESLICE_START		="input[name='TimesliceStart']";
var JS_TIMESLICE_END		="input[name='TimesliceEnd']";
var JS_OUTPUT_GROUP_ID		="input[name='OutputGroupId']";
var JS_OUTPUT_GROUP_TYPE	="select[name='OutputGroupType']";
var JS_OUTPUT_GROUP_SETTING ="input[name='OutputGroupSetting']";
var JS_OUTPUT_GROUP_CONTAINER	="select[name='OutputGroupContainer']";
var JS_OUTPUT_GROUP_URI		="input[name='OutputGroupURI']";
var JS_OUTPUT_GROUP_CUSTOM_URI	="input[name='OutputGroupCustomURI']";
var JS_OUTPUT_GROUP_PATH_URI	="input[name='OutputGroupPathURI']";
var JS_OUTPUT_GROUP_DESCRIPTION	="input[name='OutputGroupDescription']";
var JS_OUTPUT_GROUP_ACTIVE	="input[name='OutputGroupActive']";
var JS_OUTPUT_GROUP_LABEL	="input[name='OutputGroupLabel']";
var JS_CONTAINER_SETTING	= "input[name='ContainerSetting']";
var JS_BUFFER_SIZE		="input[name='BufferSize']";
var JS_SOURCE_IP = "select[name='SourceIP']";
var JS_SOURCE_IP_DOWN = "input[name='SourceIPDown']";
var JS_SOURCE_PORT = "input[name='SourcePort']";
var JS_TTL = "input[name='TTL']";
var JS_IGMP_SOURCE_IP = "input[name='IgmpSourceIp']";
var JS_OUTPUT_GROUP_PORT = "select[name='OutputGroupPort']";
var JS_OUTPUT_GROUP_PORT_DOWN = "input[name='OutputGroupPortDown']";
var JS_TARGET_NAME			="input[name='TargetName']";
var JS_EXTENSION			="input[name='Extension']";
var JS_PLAYLIST_TYPE		="select[name='PlaylistType']";
var JS_SEGMENT_LENGTH		="input[name='SegmentLength']";
var JS_SEGMENT_TYPE		="select[name='SegmentType']";
var JS_SEGMENT_RECORD_LENGTH		="select[name='SegmentRecordLength']";
var JS_EPG_FILE		="input[name='EpgFile']";
var JS_SEGMENT_NAME			="input[name='SegmentName']";
var JS_BYTE_RANGE_MODE = "input[name='byterangemode']";
var JS_PLAYLIST_NAME			="input[name='PlaylistName']";
var JS_PLAYLIST_NAME_MODE ="select[name='PlaylistNameMode']";
var JS_DISTRIBUTE_MODE ="select[name='DistributeMode']";
var JS_DISTRIBUTE_POINT ="input[name='DistributePoint']";
var JS_DELETE_UPLOADED			="select[name='DeleteUploaded']";
var JS_VOD_TARGET_NAME ="input[name='VodTargetName']";
var JS_VOD_PLAYLIST_NAME ="input[name='VodPlaylistName']";
var JS_ENCRYPTION_TYPE			="select[name='EncryptionType']";
var JS_KEY_ROTATION_COUNT		="input[name='KeyRotationCount']";
var JS_IV_FOLLOWS_SEGMENT		="input[name='IVFollowsSegment']";
var JS_IFRAME_PLAYLIST ="input[name='IframePlaylist']";
var JS_LIVE_MODE			="input[name='LiveMode']";
var JS_ROLLOVER_INTERVAL	="input[name='RolloverInterval']";
var JS_OUTPUT_ID			="input[name='OutputId']";
var JS_OUTPUT_VIDEO_BITRATE	="input[name='OutputVideoBitrate']";
var JS_PRESET_ACTION		="input[name='presetAction']";
var JS_CATEGORY				="input[name='Category']";
var JS_WATCH_FOLDER_ACTION	="input[name='watchFolderAction']";
var JS_PROFILE_ID			="select[name='ProfileId']";
var JS_WATCH_FOLDER_ACTIVE	="input[name='Active']";
var JS_WATCH_FOLDER_TYPE ="select[name='WatchFolderType']";
var JS_WATCH_FOLDER_SUBTITLE = "input[name='WatchFolderSubtitle']";
var JS_FILE_FILTER_TRIGGER	="input[name='FileFilterTrigger']";
var JS_FILE_FILTERTYPE_TRIGGER	="input[name='FileFilterTypeTrigger']";
var JS_FILE_FILTERTITLE_TEXT_TRIGGER	="span[name='FileFilterTitleText']";
var JS_IS_EXCLUDE_FILTER = "input[name='IsExcludeFilter']";
var JS_ENABLE_SUBFOLDER	="input[name='EnableSubfolder']";
var JS_FOLLOWSRCDIR			="input[name='FollowSrcDir']";
var JS_USEDEFAULTSUBTITLE	="input[name='UseDefaultSubtitle']";
var JS_FILE_FILTER			="input[name='FileFilter']";
var JS_RESOLUTION_FILTER_TRIGGER	="input[name='ResolutionFilterTrigger']";
var JS_RESOLUTION_FILTER_WIDTH	="input[name='ResolutionFilterWidth']";
var JS_RESOLUTION_FILTER_HEIGHT	="input[name='ResolutionFilterHeight']";
var JS_SCHEDULE_ACTION		="input[name='scheduleAction']";
var JS_YEAR					="select[name='Year']";
var JS_MONTH				="select[name='Month']";
var JS_DAY					="select[name='Day']";
var JS_HOUR					="select[name='Hour']";
var JS_MINUTE				="select[name='Minute']";
var JS_DAY_OF_MONTH			="select[name='DayOfMonth']";
var JS_RECURRENCE			="input[name='Recurrence']";
var JS_RECURRENCE_TYPE		="select[name='RecurrenceType']";
var JS_SCHEDULE_END_TYPE	="input[name='ScheduleEndType']";
var JS_DAILYX				="input[name='Dailyx']";
var JS_MONDAY				="input[name='Monday']";
var JS_TUESDAY				="input[name='Tuesday']";
var JS_WEDNESDAY			="input[name='Wednesday']";
var JS_THURSDAY				="input[name='Thursday']";
var JS_FRIDAY				="input[name='Friday']";
var JS_SATURDAY				="input[name='Saturday']";
var JS_SUNDAY				="input[name='Sunday']";
var JS_DAY_OF_MONTH			="select[name='DayOfMonth']";
var JS_RECURRENCE_UNTIL		="input[name='RecurrenceUntil']";
var JS_SEEK_TIME = "input[name='SeekTime']";
/**for TS setting options*/
var JS_TSAOSERVERNAME		="input[name='TsaoServerName']";
var JS_TSAOSERVERPROVIDER	="input[name='TsaoServerProvider']";
var JS_TSAOSERVICEID		="input[name='TsaoServiceID']";
var JS_TSAOPMTPID			="input[name='TsaoPmtPID']";
var JS_TSAOVIDEOPID			="input[name='TsaoVideoPID']";
var JS_TSAOAUDIOPID			="input[name='TsaoAudioPID']";
var JS_TSAOPCRPID			="input[name='TsaoPcrPID']";
/**for DRM options*/
var JS_DRMServerIP			="input[name='DRMServerIP']";
var JS_DRMENABLE			="input[name='DRMEnable']";
var JS_DRMContentId			="input[name='DRMContentId']";
var JS_DRMServerPort		="input[name='DRMServerPort']";
var JS_DRM_DESCRIPTION_TYPE ="select[name='DRMDescriptionType']";
var JS_DRM_DESCRIPTION_ENABLE ="input[name='DRMEnable']";
var JS_DRM_SETTING_TYPE ="input[name='DRMSettingType']";
var JS_DRM_CONTENT_ID ="input[name='DRMContentId']";
var JS_DRM_CUSTOMER_ID ="input[name='DRMCustomerId']";
var JS_DRM_SERVER_IP ="input[name='DRMServerIP']";
var JS_DRM_SERVER_PORT ="input[name='DRMServerPort']";
/**PIP*/
var JS_EDITOR_PIP_INSERTER	=".EditorPipInserter";
var JS_PIP_ITEM				=".PipItem";
var JS_PIP_ITEM_INDEX		=".PipItemIndex";
var JS_NEW_PIP_TRIGGER		=".NewPipTrigger";
var JS_DELETE_PIP_TRIGGER	=".DeletePipTrigger";
var JS_PIP_ITEM_CONTAINER	=".PipItemContainer";
var JS_SELECT_PIP_TRIGGER	= ".SelectPipTrigger";
var JS_PIP_MEDIA_INFO		= ".PipMediaInfo";
var JS_PIP_URI				="input[name='PipUri']";
var JS_PIP_PROGRAM_ID		="select[name='PipProgramId']";
var JS_PIP_AUDIO_TRACK_ID	="select[name='PipAudioTrackId']";
var JS_PIP_SUBTITLE_ID		="select[name='PipSubtitleId']";
var JS_PIP_INSERT_TIME		="input[name='PipInsertTime']";
var JS_PIP_X				="input[name='PipX']";
var JS_PIP_Y				="input[name='PipY']";
var JS_PIP_WIDTH			="input[name='PipWidth']";
var JS_PIP_HEIGHT			="input[name='PipHeight']";
var JS_PIP_ALPHA			="input[name='PipAlpha']";
var JS_PIP_PROGRAM_ID_DOWN	="input[name='PipProgramIdDown']";
var JS_PIP_AUDIO_TRACK_ID_DOWN	="input[name='PipAudioTrackIdDown']";
var JS_PIP_SUBTITLE_ID_DOWN	="input[name='PipSubtitleIdDown']";

/** These selector is used in template **/
var JS_INPUT_TEMPLATE			="#TemplateLib #Input";
var JS_SDI_TEMPLATE			="#TemplateLib #SDI";
var JS_CVBS_TEMPLATE			="#TemplateLib #CVBS";
var JS_HDMI_TEMPLATE			="#TemplateLib #HDMI";
var JS_AES_EBU_TEMPLATE			="#TemplateLib #AESEBU";
var JS_ASI_TEMPLATE			="#TemplateLib #ASI";
var JS_NETWORK_TEMPLATE			="#TemplateLib #Network";
var JS_LOCALFILE_TEMPLATE		="#TemplateLib #LocalFile";
var JS_BD_TEMPLATE				="#TemplateLib #BD";
var JS_DVD_TEMPLATE				="#TemplateLib #DVD";
var JS_P2_TEMPLATE				="#TemplateLib #P2";
var JS_OSS_TEMPLATE				="#TemplateLib #OSS";
var JS_COMBINATION_TEMPLATE		="#TemplateLib #COMBINATION";
var JS_OUTPUT_GROUP_TEMPLATE	="#TemplateLib #OutputGroup";
var JS_OUTPUT_TEMPLATE			="#TemplateLib #Output";
var JS_STREAM_TEMPLATE			="#TemplateLib #Stream";
var JS_VIDEO_DESCRIPTION_TEMPLATE	="#TemplateLib .VideoDescription";
var JS_VIDEO_H264_TEMPLATE		="#TemplateLib #VideoH264";
var JS_VIDEO_AVS_TEMPLATE		="#TemplateLib #VideoAVS";
var JS_VIDEO_H265_TEMPLATE		="#TemplateLib #VideoH265";
var JS_VIDEO_MPEG2_TEMPLATE		="#TemplateLib #VideoMpeg2";
var JS_VIDEO_MPEG4_TEMPLATE		="#TemplateLib #VideoMpeg4";
var JS_VIDEO_MPEG1_TEMPLATE		="#TemplateLib #VideoMpeg1";
var JS_VIDEO_WMV_TEMPLATE		="#TemplateLib #VideoWMV";
var JS_VIDEO_H263_TEMPLATE		="#TemplateLib #VideoH263";
var JS_VIDEO_DV_TEMPLATE		="#TemplateLib #VideoDV";
var JS_VIDEO_PRORES_TEMPLATE	="#TemplateLib #VideoProRes";
var JS_VIDEO_RAW_TEMPLATE	="#TemplateLib #VideoRAW";
var JS_VIDEO_DNXHD_TEMPLATE		="#TemplateLib #VideoDNxHD";
var JS_VIDEO_S263_TEMPLATE		="#TemplateLib #VideoS263";
var JS_VIDEO_PASSTHROUGH_TEMPLATE		="#TemplateLib #VideoPassThrough";
var JS_STREAM_DIALOG_TEMPLATE	="#TemplateLib #StreamDialog";
var TMP_OUTPUT_GROUP_APPLE		="#TemplateLib #AppleStreaming";
var TMP_OUTPUT_GROUP_ARCHIVE	="#TemplateLib #FileArchive";
var TMP_OUTPUT_GROUP_FLASH		="#TemplateLib #FlashStreaming";
var TMP_OUTPUT_GROUP_UDP		="#TemplateLib #UdpStreaming";
var TMP_OUTPUT_GROUP_RTP		="#TemplateLib #RtpStreaming";
var TMP_OUTPUT_GROUP_MSS		="#TemplateLib #MSStreaming";
var TMP_OUTPUT_GROUP_HTTP		="#TemplateLib #HttpStreaming";
var TMP_OUTPUT_GROUP_ASI		="#TemplateLib #AsiStreaming";
var TMP_OUTPUT_GROUP_SDI		="#TemplateLib #SdiStreaming";
var JS_TIMESLICE_TEMPLATE		="#TemplateLib .Timeslice";
var JS_MOSIAC_ITEM_TMPL			="#TemplateLib .MosaicItem";
var JS_LOGO_ITEM_TMPL			="#TemplateLib #LogoItemTmpl";
var JS_PIP_ITEM_TMPL			="#TemplateLib #PipItemTmpl";
var JS_SUBTITLE_ITEM_TMPL		="#TemplateLib #SubtitleItemTmpl";
var JS_ALTERNATE_URI_TMPL		="#TemplateLib .AlternateURI";
var JS_CANDIDATE_SDI_TMPL		="#TemplateLib .CandidateSdiItem";
var JS_JOINED_ITEM_TMPL		="#TemplateLib #JoinedItemTmpl";
var JS_SDI_JOINED_ITEM_TMPL		="#TemplateLib #SdiJoinedItemTmpl";
var JS_PROGRAM_ITEM_TMPL		="#TemplateLib #ProgramItemTmpl";
var JS_ADVERTISEMENT_ITEM_TMPL	="#TemplateLib #AdvertisementItemTmpl";
var JS_CANDIDATE_OUTPUT_TMPL ="#TemplateLib #CandidateOutputTmpl";
var JS_TS_ADVANCED_OPTIONS_TMPL = "#TemplateLib .TSAdvancedOptions";
var JS_MXF_SETTING_TMPL = "#TemplateLib .MxfSetting";
var JS_MP4_SETTING_TMPL = "#TemplateLib .Mp4Setting";
var JS_AVI_SETTING_TMPL = "#TemplateLib .AviSetting";
var JS_ES_SETTING_TMPL = "#TemplateLib .ESSetting";
var JS_TS_OVER_RTP_SETTING_TMPL = "#TemplateLib .TSOverRTPSetting";
var JS_DRM_OPTIONS_TMPL = "#TemplateLib .DRMOptions";
var JS_DRM_TIANYU_TMPL = "#TemplateLib #TianYuDRM";
var JS_DRM_ARC_TMPL = "#TemplateLib #ArcDRM";
var JS_VIDEO_DRM_ITEM_TMPL = "#TemplateLib #VideoDrmItem";
var JS_STREAM_TAB_ITEM_TMPL = "#TemplateLib #StreamTabItemTmpl";
var JS_STREAM_TAB_ITEM_TMPL2 = "#TemplateLib #StreamTabItemTmpl2";
var JS_STREAM_TAB_ITEM_TMPL3 = "#TemplateLib #StreamTabItemTmpl3";
var JS_STREAM_TAB_ITEM_TMPL4 = "#TemplateLib #StreamTabItemTmpl4";
/* */

var JS_PROFILE_LIST_DATA		="#TemplateLib #ProfileListData";
var JS_PRESET_LIST_DATA			="#TemplateLib #PresetListData";
var JS_CATEGORY_LIST_DATA		="#TemplateLib #CategoryListData";

/** tag definition used in xml**/
var TAG_ENABLED				="enabled";
var TAG_X = "x";
var TAG_Y = "y";
var TAG_LEFT				="left";
var TAG_TOP					="top";
var TAG_WIDTH				="width";
var TAG_HEIGHT				="height";
var TAG_OPACITY = "opacity";
var TAG_RESIZE = "resize";
var TAG_ID					="id";
var TAG_ACTION				="action";
var TAG_NAME				="name";
var TAG_DESCRIPTION			="description";
var TAG_URI ="uri";
var TAG_START = "start";
var TAG_END = "end";
var TAG_PROGRAM_ID ="programid";
var TAG_AUDIO_TRACK_ID ="audiotrackid";
var TAG_SUBTITLE_ID ="subtitleid";
var TAG_TASK_ACTION			="taskaction";
var TAG_TASK_FLAG			="taskflag";
var TAG_PROFILE_ACTION		="profileaction";
var TAG_PAGE_NAME			="pagename";
var TAG_TASK				="task";
var TAG_STREAMS				="streams";
var TAG_INPUTS				="inputs";
var TAG_OUTPUT_GROUPS		="outputgroups";
var TAG_APPLE_STREAMING		="applestreaming";
var TAG_FILE_ARCHIVE		="filearchive";
var TAG_FLASH_STREAMING		="flashstreaming";
var TAG_UDP_STREAMING		="udpstreaming";
var TAG_RTP_STREAMING		="rtpstreaming";
var TAG_MS_STREAMING		="msstreaming";
var TAG_HTTP_STREAMING		="httpstreaming";
var TAG_ASI_STREAMING		="asistreaming";
var TAG_SDI_STREAMING		="sdistreaming";
var TAG_PROFILE				="profile";
var TAG_STREAM				="stream";
var TAG_ENCODING_OPTION		="encodingoption";
var TAG_PRIORITY			="priority";
var TAG_GPUID			="gpuid";
var TAG_VIDEO_DECODING			="videodecoding";
var TAG_POST_PROCESS		="postprocess";
var TAG_GLOBAL_CODEC_SETTING		="globalcodecsetting";
var TAG_FILL_ON_STREAM_LOST = "fillonstreamlost";
/**for ts setting tag name*/
var TAG_TS_SETTING			="tssetting";
var TAG_TS_SETTING_SERVERNAME = "servername";
var TAG_TS_SETTING_SERVICEPROVIDER = "serviceprovider";
var TAG_TS_SETTING_SERVICEID = "serviceid";
var TAG_TS_SETTING_PMTPID = "pmtpid";
var TAG_TS_SETTING_VIDEOPID = "videopid";
var TAG_TS_SETTING_AUDIOPID = "audiopid";
var TAG_TS_SETTING_PCRPID = "pcrpid";
/**for HLS's DRM tag name*/
var TAG_HLS_TIANYUDRM		="tianyudrm";
var TAG_HLS_ENABLED			="enabled";
var TAG_HLS_SERVERIP		="serverip";
var TAG_HLS_SERVERPORT		="serverport";
var TAG_HLS_CONTENTID		="contentid";
var TAG_INPUT				="input";
var TAG_SDI					="sdi";
var TAG_CVBS					="cvbs";
var TAG_HDMI					="hdmi";
var TAG_AES_EBU					="aesebu";
var TAG_ASI					="asi";
var TAG_NETWORK				="network";
var TAG_LOCAL_FILE			="localfile";
var TAG_BD					="bd";
var TAG_DVD					="dvd";
var TAG_P2					="p2";
var TAG_OSS					="oss";
var TAG_COMBINATION			="combination";
var TAG_INPUT_TYPE 			="type";
var TAG_INPUT_URI			="uri";
var TAG_INPUT_PREPROCESSOR	="preprocessor";
var TAG_INPUT_FORMAT		="inputformat";
var TAG_INPUT_FAILOVER_TIME	="failovertime";
var TAG_INPUT_PORT		="port";
var TAG_INPUT_LIVE_SYNC_MODE ="livesyncmode";
var TAG_INPUT_KEY		="key";
var TAG_INPUT_PROGRAM_ID	="programid";
var TAG_INPUT_AUDIO_TRACK_ID	="audiotrackid";
var TAG_INPUT_SUBTITLE_ID	="subtitleid";
var TAG_INPUT_ANGLE_ID	="angleid";
var TAG_INPUT_AUDIO_CHANNEL_ID	="audiochannelid";
var TAG_INPUT_4K	="input4k";
var TAG_INPUT_PROTOCOL		="protocol";
var TAG_JOINED_INPUT_TYPE = "inputtype";
var TAG_TIMESLICE_CLIPPING	="timesliceclipping";
var TAG_TIMESLICE_ENABLED	="enabled";
var TAG_TIMESLICE_TRIMMED	="trimmed";
var TAG_TIMESLICES			="timeslices";
var TAG_TIMESLICE			="timeslice";
var TAG_TIMESLICE_START		="start";
var TAG_TIMESLICE_END		="end";
var TAG_CROPPING			="cropping";
var TAG_MOSAIC				="mosaic";
var TAG_MOSAIC_BLUR			="grain";
var TAG_MOSAIC_TYPE			="type";
var TAG_MOSAIC_ACTIVE_TIME	="activetime";
var TAG_MOSAIC_START		="start";
var TAG_MOSAIC_END			="end";
var TAG_TIMECLIPPING		="timesliceclipping";
var TAG_TIMECLIPPING_TRIMMED	="trimmed";
var TAG_OUTPUT_GROUP		="outputgroup";
var TAG_OUTPUT_GROUP_TYPE	="type";
var TAG_OUTPUT_GROUP_CONTAINER	="container";
var TAG_OUTPUT_GROUP_URI	="uri";
var TAG_OUTPUT_GROUP_PATH_URI	="pathuri";
var TAG_SEGMENT_LENGTH		="segmentlength";
var TAG_SEGMENT_RECORD_LENGTH = "segmentrecordlength";
var TAG_SEGMENT_TYPE = "segmenttype";
var TAG_EPG_FILE = "epgfile";
var TAG_SEGMENT_NAME		="segmentname";
var TAG_BYTE_RANGE_MODE     = "byterangemode";
var TAG_PLAYLIST_NAME		="playlistname";
var TAG_PLAYLIST_NAME_MODE		="playlistnamemode";
var TAG_IFRAME_PLAYLIST ="iframeplaylist";
var TAG_PLAYLIST_TYPE = "playlisttype";
var TAG_DELETE_UPLOADED		="deleteuploaded";
var TAG_ENCRYPTION_TYPE		="encryptiontype";
var TAG_KEY_ROTATION_COUNT	="keyrotationcount";
var TAG_IV_FOLLOWS_SEGMENT	="ivfollowssegment";
var TAG_LIVE_MODE			="livemode";
var TAG_DISTRIBUTE_MODE			="distributemode";
var TAG_VOD_TARGET_NAME = "vodtargetname";
var TAG_VOD_PLAYLIST_NAME = "vodplaylistname";
var TAG_ROLLOVER_INTERVAL	="rolloverinterval";
var TAG_TARGET_NAME			="targetname";
var TAG_EXTENSION			="extension";
var TAG_SOURCE_IP		="srcip";
var TAG_INPUT_VIDEO_RTP_URI = "videortpuri";
var TAG_INPUT_AUDIO_RTP_URI = "audiortpuri";
var TAG_INPUT_VIDEO_RTCP_URI = "videortcpuri";
var TAG_INPUT_AUDIO_RTCP_URI = "audiortcpuri";
var TAG_INPUT_SDP = "sdp";
var TAG_INPUT_ALLOW_PROGRAM_ID_CHANGE = "allowprogramidchange";
var TAG_INPUT_FILL_TYPE = "filltype";
var TAG_DELAY_OUTPUT_TIME = "delayoutputtime";
var TAG_FILL_LOST_TIME = "filllosttime";
var TAG_FILL_MODE_LOST = "fillmodelost";
var TAG_SOURCE_PORT		="srcport";
var TAG_BUFFER_SIZE		="buffersize";
var TAG_TTL		="ttl";
var TAG_IGMP_SOURCE_IP		="igmpsourceip";
var TAG_OUTPUT_VIDEO_BITRATE	="bitrate";
var TAG_PRESET				="preset";
var TAG_PRESET_ACTION		="presetAction";
var TAG_CATEGORY			="category";
var TAG_WATCH_FOLDER		="watchfolder";
var TAG_PROFILE_ID			="profileid";
var TAG_ACTIVE				="active";
var TAG_FILTER_PATTERN		="filterpattern";
var TAG_FILTER				="filter";
var TAG_SCHEDULE			="schedule";
var TAG_START_TIME			="starttime";
var TAG_END_TIME			="endtime";
var TAG_END_TYPE			="endtype";
var TAG_RECURRENCE_PATTERN	="recurrencepattern";
var TAG_RECURRENCE			="recurrence";
var TAG_RECURRENCE_TYPE		="recurrencetype";
var TAG_DAILY				="daily";
var TAG_WEEKLY				="weekly";
var TAG_WEEKLYX				="weeklyx";
var TAG_MONTHLY				="monthly";
var TAG_MONTHLYX			="monthlyx";
var TAG_MONTHLYBY			="monthlyby";
var TAG_DAILYX				="dailyx";
var TAG_SUNDAY				="sunday";
var TAG_MONDAY				="monday";
var TAG_TUESDAY				="tuesday";
var TAG_WEDNESDAY			="wednesday";
var TAG_THURSDAY			="thursday";
var TAG_FRIDAY				="friday";
var TAG_SATURDAY			="saturday";
var TAG_DAY_OF_MONTH		="dayofmonth";
var TAG_END_OPTION			="endoption";
var TAG_UNTIL				="until";
var TAG_END_DATE			="enddate";
var TAG_ADVERTISEMENT = "advertisement";
var TAG_CLIP = "clip";
var TAG_ENTRY = "entry";
var TAG_MV4ENLIGHT = "mv4enlight";
var TAG_TOTAL_DURATION = "totalduration";
var TAG_PADDING = "padding";
var TAG_PADDING_LOGO_URI = "logouri";
var TAG_LOGO ="logo";
var TAG_PRESET_ID = "presetid";
var TAG_PIP = "pip";
var TAG_POS_X = "posx";
var TAG_POS_Y = "posy";
var TAG_ALPHA = "alpha";
var TAG_INSERT_TIME = "inserttime";
var TAG_DRM_DESCRIPTION ="drm";
var TAG_DRM_DESCRIPTION_TYPE ="type";
var TAG_DRM_DESCRIPTION_ENABLE ="enabled";
var TAG_DRM_CONTENT_ID ="contentid";
var TAG_DRM_CUSTOMER_ID ="customerid";
var TAG_DRM_SERVER_IP ="serverip";
var TAG_DRM_SERVER_PORT ="serverport";
/* Tag end */

/* Field definition */
var FIELD_MODEL				="task";
var FIELD_PROFILE			="liveProfile";
var FIELD_ID				="id";
var FIELD_GUID				="userData";
var FIELD_NAME				="name";
var FIELD_ENCODING_OPTION	="encodingOption";
var FIELD_PRIORITY			="priority";
var FIELD_GPUID			="gpuId";
var FIELD_VIDEO_DECODING	="videoDecoding";
var FIELD_SCRIPT_URI		="postProcess.uri";
var FIELD_FILL_ON_STREAM_LOST		="globalCodecSetting.fillOnStreamLost";
var FIELD_DESCRIPTION		="description";
var FIELD_INPUT				="inputs";
var FIELD_INPUT_TYPE 		="videoInputType";
var FIELD_INPUT_BODY		="body";
var FIELD_INPUT_PORT		="body.channel";
var FIELD_INPUT_LIVE_SYNC_MODE ="body.liveSyncMode";
var FIELD_INPUT_KEY		="body.key";
var FIELD_INPUT_URI			="body.uri";
var FIELD_INPUT_FORMAT		="body.inputFormat";
var FIELD_INPUT_FAILOVER_TIME	="failoverTime";
var FIELD_INPUT_SRC_IP ="body.srcIp";
var FIELD_INPUT_VIDEO_RTP_URI	="body.videoRtpUri";
var FIELD_INPUT_AUDIO_RTP_URI	="body.audioRtpUri";
var FIELD_INPUT_VIDEO_RTCP_URI	="body.videoRtcpUri";
var FIELD_INPUT_AUDIO_RTCP_URI	="body.audioRtcpUri";
var FIELD_INPUT_SDP	="body.sdp";
var FIELD_INPUT_PROGRAM_ID	="programId";
var FIELD_INPUT_AUDIO_TRACK_ID	="audioTrackId";
var FIELD_INPUT_SUBTITLE_ID	="subtitleId";
var FIELD_INPUT_ANGLE_ID	="angleId";
var FIELD_INPUT_AUDIO_CHANNEL_ID	="audioChannelId";
var FIELD_INPUT_4K	="body.input4k";
var FIELD_INPUT_PROTOCOL	="body.protocol";
var FIELD_INPUT_FILL_TYPE = "fillType";
var FIELD_DELAY_OUTPUT_TIME = "delayOutputTime";
var FIELD_FILL_LOST_TIME = "fillLostTime";
var FIELD_INPUT_ALLOW_PROGRAM_ID_CHANGE = "body.allowProgramIdChange";
var FIELD_FILL_MODE_LOST = "fillModeLost";
var FIELD_MOSAIC			="mosaicInserter";
var FIELD_MOSAICS			="mosaicInserters";
var FIELD_MOSAIC_ENABLE		="enabled";
var FIELD_MOSAIC_BLUR		="grain";
var FIELD_MOSAIC_X			="imageX";
var FIELD_MOSAIC_Y			="imageY";
var FIELD_MOSAIC_WIDTH		="imageWidth";
var FIELD_MOSAIC_HEIGHT		="imageHeight";
var FIELD_MOSAIC_ACTIVE_TIME="activeTime";
var FIELD_MOSAIC_START		="start";
var FIELD_MOSAIC_END		="end";
var FIELD_MOSAIC_TYPE		="mosaicType";
var FIELD_TRIM				="cropping";
var FIELD_TRIM_ENABLE		="enabled";
var FIELD_TRIM_X			="x";
var FIELD_TRIM_Y			="y";
var FIELD_TRIM_WIDTH		="width";
var FIELD_TRIM_HEIGHT		="height";
var FIELD_TIMECLIPPING		="timesliceClipping";
var FIELD_TIMECLIPPING_ENABLE	="enabled";
var FIELD_TIMECLIPPING_TRIMMED	="trimmed";
var FIELD_TIMESLICES		="timeslices";
var FIELD_TIMESLICE_START	="start";
var FIELD_TIMESLICE_END		="end";
var FIELD_OUTPUT_GROUP		="outputGroups";
var FIELD_OUTPUT_GROUP_TYPE	="settingsType";
var FIELD_OUTPUT_GROUP_SETTING	="outputGroupSetting";
var FIELD_OUTPUT_GROUP_CONTAINER	="container";
var FIELD_OUTPUT_GROUP_URI	="outputGroupSetting.location.uri";
var FIELD_OUTPUT_GROUP_CUSTOM_URI	="outputGroupSetting.customUri";
var FIELD_OUTPUT_GROUP_PATH_URI	="outputGroupSetting.pathUri";
var FIELD_SEGMENT_LENGTH	="outputGroupSetting.segmentLength";
var FIELD_SEGMENT_RECORD_LENGTH	="outputGroupSetting.segmentRecordLength";
var FIELD_SEGMENT_TYPE	="outputGroupSetting.segmentType";
var FIELD_PLAYLIST_TYPE	="outputGroupSetting.playlistType";
var FIELD_EPG_FILE	="outputGroupSetting.epgFile";
var FIELD_SEGMENT_NAME	="outputGroupSetting.segmentName";
var FIELD_BYTE_RANGE_MODE ="outputGroupSetting.byteRangeMode"; 
var FIELD_PLAYLIST_NAME	="outputGroupSetting.playlistName";
var FIELD_PLAYLIST_NAME_MODE	="outputGroupSetting.playlistNameMode";
var FIELD_DELETE_UPLOADED	="outputGroupSetting.deleteUploaded";
var FIELD_ENCRYPTION_TYPE	="outputGroupSetting.encryptionType";
var FIELD_KEY_ROTATION_COUNT	="outputGroupSetting.keyRotationCount";
var FIELD_IV_FOLLOWS_SEGMENT	="outputGroupSetting.ivFollowsSegmentNumber";
var FIELD_IFRAME_PLAYLIST	="outputGroupSetting.iframePlaylist";
var FIELD_LIVE_MODE			="outputGroupSetting.liveMode";
var FIELD_DISTRIBUTE_MODE			="outputGroupSetting.distributeMode";
var FIELD_VOD_TARGET_NAME			="outputGroupSetting.vodTargetName";
var FIELD_VOD_PLAYLIST_NAME			="outputGroupSetting.vodPlaylistName";
var FIELD_TARGET_NAME		="outputGroupSetting.targetName";
var FIELD_EXTENSION			="outputGroupSetting.extension";
var FIELD_OUTPUTGROUP_SETTING_BUFFER_SIZE	="outputGroupSetting.bufferSize";
var FIELD_OUTPUTGROUP_SETTING_TTL		="outputGroupSetting.ttl";
var FIELD_OUTPUTGROUP_IGMP_SOURCE_IP		="outputGroupSetting.igmpSourceIp";
var FIELD_SOURCE_IP		="srcIp";
var FIELD_SOURCE_PORT		="srcPort";
var FIELD_PORT			="port";
var FIELD_BUFFER_SIZE	="bufferSize";
var FIELD_TTL		="ttl";
var FIELD_IGMP_SOURCE_IP		="igmpSourceIp";
var FIELD_CONTAINER_SETTING ="containerSetting";
var FIELD_STREAM			="streamAssemblys";
var FIELD_STREAMASSEMBLY	="streamAssembly";
var FIELD_PRESET			="preset";
var FIELD_PRESET_ACTION		="presetAction";
var FIELD_CATEGORY			="presetCategory.name";
var FIELD_WATCH_FOLDER		="watchFolder";
var FIELD_WATCH_FOLDER_ACTION	="watchFolderAction";
var FIELD_FOLDER			="folder";
var FIELD_PROFILE_ID		="profileId";
var FIELD_ACTIVE			="active";
var FIELD_ENABLE_FILTER		="enableFilter";
var FIELD_IS_EXCLUDE_FILTER ="isExcludeFilter";
var FIELD_ENABLE_SUBFOLDER = "enableSubfolder";
var FIELD_FOLLOW_SRC_DIR 	= "followSrcDir";
var FIELD_FILTER			="filter";
var FIELD_RESOLUTION_ENABLE = "resolutionFilter.enabled";
var FIELD_RESOLUTION_WIDTH = "resolutionFilter.width";
var FIELD_RESOLUTION_HEIGHT = "resolutionFilter.height";
var FIELD_TYPE				="type";
var FIELD_SUBTITLE			="subtitle";
var FIELD_USE_DEFAULT_SUBTITLE			="useDefaultSubtitle";
var FIELD_SCHEDULE			="schedule";
var FIELD_START_TIME		="startTime";
var FIELD_END_TIME			="endTime";
var FIELD_END_TYPE			="endType";
var FIELD_SCHEDULE_TYPE		="scheduleType";
var FIELD_DAILYX			="dailyX";
var FIELD_DAY_OF_MONTH		="dayOfMonth";
var FIELD_SUNDAY			="sunday";
var FIELD_MONDAY			="monday";
var FIELD_TUESDAY			="tuesday";
var FIELD_WEDNESDAY			="wednesday";
var FIELD_THURSDAY			="thursday";
var FIELD_FRIDAY			="friday";
var FIELD_SATURDAY			="saturday";
var FIELD_UNTIL				="until";
var FIELD_END_DATE			="endDate";
var FIELD_DRM_DESCRIPTION = "drmDescription";
var FIELD_DRM_DESCRIPTION_TYPE ="settingsType";
var FIELD_DRM_DESCRIPTION_ENABLE ="enabled";
var FIELD_DRM_SETTING_TYPE ="drmSetting";
var FIELD_DRM_CONTENT_ID ="drmSetting.contentId";
var FIELD_DRM_CUSTOMER_ID ="drmSetting.customerId";
var FIELD_DRM_SERVER_IP ="drmSetting.serverIP";
var FIELD_DRM_SERVER_PORT ="drmSetting.serverPort";
/* Field end */

/* schedule selector */
var JS_START_TIME		="input[name='startTime']";
var JS_END_TIME			="input[name='endTime']";
var JS_SCHEDULE_TYPE	="input[name='scheduleType']";
var JS_END_DATE			="input[name='endDate']";

/** key definition **/

var INPUT_MOVE_PREV = "MovePrev";
var INPUT_MOVE_NEXT = "MoveNext";

/** Page name **/
var PAGE_LIST_TASK		="listTask";
var PAGE_LIST_PROFILE	="listProfile";
var PAGE_LIST_SCHEDULE	="listSchedule";
var PAGE_LIST_PRESET	="listPreset";
var PAGE_LIST_WATCH_FOLDER	="listWatchFolder";
var PAGE_LIST_SCHEDULE	="listSchedule";

var PAGE_NAME_TASK		="TaskBody";
var PAGE_NAME_PROFILE	="ProfileBody";
var PAGE_NAME_SCHEDULE	="ScheduleBody";

var NEW_OUTPUT_LITTLE_STREAM = "LittleStream";
var NEW_OUTPUT_BIG_STREAM = "BigStream";
var NEW_OUTPUT_FROM_PRESET = "FromPreset";
var OUTPUT_NEW_DEFAULT = "NewDefault";
var OUTPUT_IMPORT_FROM_PRESET = "ImportFromPreset";

//ENABLE value
var ENABLE_TRUE = "true";
var ENABLE_FALSE = "false";

var MAX_INTEGER = 2147483647;
var MIN_INTEGER = -2147483647;

/*used in time clipping*/
var MAX_COUNT_TIME_SLICES = 99;
var MAX_COUNT_MOSAIC_ITEM = 10;
var MAX_COUNT_LOGO_ITEM = 4;
var MAX_COUNT_PIP_ITEM = 4;
var MAX_COUNT_ADVERTISEMENT_ITEM = 10;
var MAX_COUNT_AUDIO = 8;
var MAX_COUNT_SUBTITLE_ITEM = 5;

/*from tmplayer define*/
var PLAYER_MEDIA_TYPE_FILE = 0;
var PLAYER_MEDIA_TYPE_BD = 1;
var PLAYER_MEDIA_TYPE_DVD = 2;
var PLAYER_MEDIA_TYPE_UDP = 3;

/*TMPlayer state*/
var STATE_CLOSED = 0;
var STATE_STOPPED = 1;
var STATE_PAUSED = 2;
var STATE_RUNNING = 3; 
var STATE_INITING = 4;

var LINKED_PRESET_ID_NONE = "-1";

var ACTION_TYPE_SAVE = "save";
var ACTION_TYPE_UPDATE = "update";

var MATERIAL_TYPE_DYNAMICTEXT = "1";
var MATERIAL_TYPE_MOTIONICON = "2";
var MATERIAL_TYPE_LOGO = "3";
var MATERIAL_TYPE_PADDING = "4";

/** global **/
var g_PopBackground = null;
var g_focusOutput = null;
var g_OutputGroupTab = null;
var g_InputFileView = null;
var g_InputBDSelector = null;
var g_OutputFileView = null;
var g_OutputFileViewOwner = null;
var g_LogoFileView = null;
var g_SubtitleFileView = null;
var g_AdvertisementFileView = null;
var g_domScheduleDetail = null;
var g_SaveAsProfile = null;
var g_SaveAsPreset = null;
var g_SaveAsPresetStream = null;
var g_OutputGroupFocus = null;
var g_taskSupport = null;
var g_scheduleSupport = null;
var g_categoryList = null;
var g_SDIPreview = null;
var g_ProgramPreview = null;
var g_InputPreview = null;
var g_InputPreviewOwner = null;
var g_OutputPreview = null;
var g_OutputPreviewOwner = null;
var g_ScriptFileView = null;
var g_Focus = null;
var g_LineSelector = null;

//Action params
var g_params_listIfaces = {};
var g_params_getMediaFileInfo = {};
var g_params_preview_action = {};
var g_params_setRuntimeTask = {};
