var languageMap = [
{key:"aar", value: "Afar"},
{key:"abk", value: "Abkhazian"},
{key:"ace", value: "Achinese"},
{key:"ach", value: "Acoli"},
{key:"ada", value: "Adangme"},
{key:"ady", value: "Adyghe; Adygei"},
{key:"afa", value: "Afro-Asiatic (Other)"},
{key:"afh", value: "Afrihili"},
{key:"afr", value: "Afrikaans"},
{key:"ain", value: "Ainu"},
{key:"aka", value: "Akan"},
{key:"akk", value: "Akkadian"},
{key:"alb", value: "Albanian"},
{key:"ale", value: "Aleut"},
{key:"alg", value: "Algonquian languages"},
{key:"alt", value: "Southern Altai"},
{key:"amh", value: "Amharic"},
{key:"ang", value: "English, Old (ca.450-1100)"},
{key:"anp", value: "Angika"},
{key:"apa", value: "Apache languages"},
{key:"ara", value: "Arabic"},
{key:"arc", value: "Aramaic"},
{key:"arg", value: "Aragonese"},
{key:"arm", value: "Armenian"},
{key:"arn", value: "Araucanian"},
{key:"arp", value: "Arapaho"},
{key:"art", value: "Artificial (Other)"},
{key:"arw", value: "Arawak"},
{key:"asm", value: "Assamese"},
{key:"ast", value: "Asturian; Bable"},
{key:"ath", value: "Athapascan languages"},
{key:"aus", value: "Australian languages"},
{key:"ava", value: "Avaric"},
{key:"ave", value: "Avestan"},
{key:"awa", value: "Awadhi"},
{key:"aym", value: "Aymara"},
{key:"aze", value: "Azerbaijani"},
{key:"bad", value: "Banda"},
{key:"bai", value: "Bamileke languages"},
{key:"bak", value: "Bashkir"},
{key:"bal", value: "Baluchi"},
{key:"bam", value: "Bambara"},
{key:"ban", value: "Balinese"},
{key:"baq", value: "Basque"},
{key:"bas", value: "Basa"},
{key:"bat", value: "Baltic (Other)"},
{key:"bej", value: "Beja"},
{key:"bel", value: "Belarusian"},
{key:"bem", value: "Bemba"},
{key:"ben", value: "Bengali"},
{key:"ber", value: "Berber (Other)"},
{key:"bho", value: "Bhojpuri"},
{key:"bih", value: "Bihari"},
{key:"bik", value: "Bikol"},
{key:"bin", value: "Bini"},
{key:"bis", value: "Bislama"},
{key:"bla", value: "Siksika"},
{key:"bnt", value: "Bantu (Other)"},
{key:"tib", value: "Tibetan"},
{key:"bod", value: "Tibetan"},
{key:"bos", value: "Bosnian"},
{key:"bra", value: "Braj"},
{key:"bre", value: "Breton"},
{key:"btk", value: "Batak (Indonesia)"},
{key:"bua", value: "Buriat"},
{key:"bug", value: "Buginese"},
{key:"bul", value: "Bulgarian"},
{key:"bur", value: "Burmese"},
{key:"byn", value: "Blin; Bilin"},
{key:"cad", value: "Caddo"},
{key:"cai", value: "Central American Indian (Other)"},
{key:"car", value: "Carib"},
{key:"cat", value: "Catalan; Valencian"},
{key:"cau", value: "Caucasian (Other)"},
{key:"ceb", value: "Cebuano"},
{key:"cel", value: "Celtic (Other)"},
{key:"ces", value: "Czech"},
{key:"cze", value: "Czech"},
{key:"cha", value: "Chamorro"},
{key:"chb", value: "Chibcha"},
{key:"che", value: "Chechen"},
{key:"chg", value: "Chagatai"},
{key:"chi", value: "Chinese"},
{key:"chk", value: "Chuukese"},
{key:"chm", value: "Mari"},
{key:"chn", value: "Chinook jargon"},
{key:"cho", value: "Choctaw"},
{key:"chp", value: "Chipewyan"},
{key:"chr", value: "Cherokee"},
{key:"chu", value: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"},
{key:"chv", value: "Chuvash"},
{key:"chy", value: "Cheyenne"},
{key:"cmc", value: "Chamic languages"},
{key:"cop", value: "Coptic"},
{key:"cor", value: "Cornish"},
{key:"cos", value: "Corsican"},
{key:"cpe", value: "Creoles and pidgins, English based (Other)"},
{key:"cpf", value: "Creoles and pidgins, French-based (Other)"},
{key:"cpp", value: "Creoles and pidgins, Portuguese-based (Other)"},
{key:"cre", value: "Cree"},
{key:"crh", value: "Crimean Tatar; Crimean Turkish"},
{key:"crp", value: "Creoles and pidgins (Other)"},
{key:"csb", value: "Kashubian"},
{key:"cus", value: "Cushitic (Other)"},
{key:"cym", value: "Welsh"},
{key:"wel", value: "Welsh"},
{key:"cze", value: "Czech"},
{key:"dak", value: "Dakota"},
{key:"dan", value: "Danish"},
{key:"dar", value: "Dargwa"},
{key:"day", value: "Dayak"},
{key:"del", value: "Delaware"},
{key:"den", value: "Slave (Athapascan)"},
{key:"deu", value: "German"},
{key:"ger", value: "German"},
{key:"dgr", value: "Dogrib"},
{key:"din", value: "Dinka"},
{key:"div", value: "Divehi; Dhivehi; Maldivian"},
{key:"doi", value: "Dogri"},
{key:"dra", value: "Dravidian (Other)"},
{key:"dsb", value: "Lower Sorbian"},
{key:"dua", value: "Duala"},
{key:"dum", value: "Dutch, Middle (ca.1050-1350)"},
{key:"dut", value: "Dutch; Flemish"},
{key:"dyu", value: "Dyula"},
{key:"dzo", value: "Dzongkha"},
{key:"efi", value: "Efik"},
{key:"egy", value: "Egyptian (Ancient)"},
{key:"eka", value: "Ekajuk"},
{key:"gre", value: "Greek, Modern (1453-)"},
{key:"ell", value: "Greek, Modern (1453-)"},
{key:"elx", value: "Elamite"},
{key:"eng", value: "English"},
{key:"enm", value: "English, Middle (1100-1500)"},
{key:"epo", value: "Esperanto"},
{key:"est", value: "Estonian"},
{key:"eus", value: "Basque"},
{key:"baq", value: "Basque"},
{key:"ewe", value: "Ewe"},
{key:"ewo", value: "Ewondo"},
{key:"fan", value: "Fang"},
{key:"fao", value: "Faroese"},
{key:"fas", value: "Persian"},
{key:"per", value: "Persian"},
{key:"fat", value: "Fanti"},
{key:"fij", value: "Fijian"},
{key:"fil", value: "Filipino; Pilipino"},
{key:"fin", value: "Finnish"},
{key:"fiu", value: "Finno-Ugrian (Other)"},
{key:"fon", value: "Fon"},
{key:"fra", value: "French"},
{key:"fre", value: "French"},
{key:"frm", value: "French, Middle (ca.1400-1600)"},
{key:"fro", value: "French, Old (842-ca.1400)"},
{key:"frr", value: "Northern Frisian"},
{key:"frs", value: "Eastern Frisian"},
{key:"fry", value: "Western Frisian"},
{key:"ful", value: "Fulah"},
{key:"fur", value: "Friulian"},
{key:"gaa", value: "Ga"},
{key:"gay", value: "Gayo"},
{key:"gba", value: "Gbaya"},
{key:"gem", value: "Germanic (Other)"},
{key:"geo", value: "Georgian"},
{key:"ger", value: "German"},
{key:"gez", value: "Geez"},
{key:"gil", value: "Gilbertese"},
{key:"gla", value: "Gaelic; Scottish Gaelic"},
{key:"gle", value: "Irish"},
{key:"glg", value: "Galician"},
{key:"glv", value: "Manx"},
{key:"gmh", value: "German, Middle High (ca.1050-1500)"},
{key:"goh", value: "German, Old High (ca.750-1050)"},
{key:"gon", value: "Gondi"},
{key:"gor", value: "Gorontalo"},
{key:"got", value: "Gothic"},
{key:"grb", value: "Grebo"},
{key:"grc", value: "Greek, Ancient (to 1453)"},
{key:"gre", value: "Greek, Modern (1453-)"},
{key:"grn", value: "Guarani"},
{key:"gsw", value: "Alemani; Swiss German"},
{key:"guj", value: "Gujarati"},
{key:"gwi", value: "Gwich´in"},
{key:"hai", value: "Haida"},
{key:"hat", value: "Haitian; Haitian Creole"},
{key:"hau", value: "Hausa"},
{key:"haw", value: "Hawaiian"},
{key:"heb", value: "Hebrew"},
{key:"her", value: "Herero"},
{key:"hil", value: "Hiligaynon"},
{key:"him", value: "Himachali"},
{key:"hin", value: "Hindi"},
{key:"hit", value: "Hittite"},
{key:"hmn", value: "Hmong"},
{key:"hmo", value: "Hiri Motu"},
{key:"scr", value: "Croatian"},
{key:"hrv", value: "Croatian"},
{key:"hsb", value: "Upper Sorbian"},
{key:"hun", value: "Hungarian"},
{key:"hup", value: "Hupa"},
{key:"hye", value: "Armenian"},
{key:"arm", value: "Armenian"},
{key:"iba", value: "Iban"},
{key:"ibo", value: "Igbo"},
{key:"ice", value: "Icelandic"},
{key:"ido", value: "Ido"},
{key:"iii", value: "Sichuan Yi"},
{key:"ijo", value: "Ijo"},
{key:"iku", value: "Inuktitut"},
{key:"ile", value: "Interlingue"},
{key:"ilo", value: "Iloko"},
{key:"ina", value: "Interlingua (International Auxiliary Language Association)"},
{key:"inc", value: "Indic (Other)"},
{key:"ind", value: "Indonesian"},
{key:"ine", value: "Indo-European (Other)"},
{key:"inh", value: "Ingush"},
{key:"ipk", value: "Inupiaq"},
{key:"ira", value: "Iranian (Other)"},
{key:"iro", value: "Iroquoian languages"},
{key:"isl", value: "Icelandic"},
{key:"ice", value: "Icelandic"},
{key:"ita", value: "Italian"},
{key:"jav", value: "Javanese"},
{key:"jbo", value: "Lojban"},
{key:"jpn", value: "Japanese"},
{key:"jpr", value: "Judeo-Persian"},
{key:"jrb", value: "Judeo-Arabic"},
{key:"kaa", value: "Kara-Kalpak"},
{key:"kab", value: "Kabyle"},
{key:"kac", value: "Kachin"},
{key:"kal", value: "Kalaallisut; Greenlandic"},
{key:"kam", value: "Kamba"},
{key:"kan", value: "Kannada"},
{key:"kar", value: "Karen"},
{key:"kas", value: "Kashmiri"},
{key:"kat", value: "Georgian"},
{key:"geo", value: "Georgian"},
{key:"kau", value: "Kanuri"},
{key:"kaw", value: "Kawi"},
{key:"kaz", value: "Kazakh"},
{key:"kbd", value: "Kabardian"},
{key:"kha", value: "Khasi"},
{key:"khi", value: "Khoisan (Other)"},
{key:"khm", value: "Khmer"},
{key:"kho", value: "Khotanese"},
{key:"kik", value: "Kikuyu; Gikuyu"},
{key:"kin", value: "Kinyarwanda"},
{key:"kir", value: "Kirghiz"},
{key:"kmb", value: "Kimbundu"},
{key:"kok", value: "Konkani"},
{key:"kom", value: "Komi"},
{key:"kon", value: "Kongo"},
{key:"kor", value: "Korean"},
{key:"kos", value: "Kosraean"},
{key:"kpe", value: "Kpelle"},
{key:"krc", value: "Karachay-Balkar"},
{key:"krl", value: "Karelian"},
{key:"kro", value: "Kru"},
{key:"kru", value: "Kurukh"},
{key:"kua", value: "Kuanyama; Kwanyama"},
{key:"kum", value: "Kumyk"},
{key:"kur", value: "Kurdish"},
{key:"kut", value: "Kutenai"},
{key:"lad", value: "Ladino"},
{key:"lah", value: "Lahnda"},
{key:"lam", value: "Lamba"},
{key:"lao", value: "Lao"},
{key:"lat", value: "Latin"},
{key:"lav", value: "Latvian"},
{key:"lez", value: "Lezghian"},
{key:"lim", value: "Limburgan; Limburger; Limburgish"},
{key:"lin", value: "Lingala"},
{key:"lit", value: "Lithuanian"},
{key:"lol", value: "Mongo"},
{key:"loz", value: "Lozi"},
{key:"ltz", value: "Luxembourgish; Letzeburgesch"},
{key:"lua", value: "Luba-Lulua"},
{key:"lub", value: "Luba-Katanga"},
{key:"lug", value: "Ganda"},
{key:"lui", value: "Luiseno"},
{key:"lun", value: "Lunda"},
{key:"luo", value: "Luo (Kenya and Tanzania)"},
{key:"lus", value: "Lushai"},
{key:"mac", value: "Macedonian"},
{key:"mad", value: "Madurese"},
{key:"mag", value: "Magahi"},
{key:"mah", value: "Marshallese"},
{key:"mai", value: "Maithili"},
{key:"mak", value: "Makasar"},
{key:"mal", value: "Malayalam"},
{key:"man", value: "Mandingo"},
{key:"mao", value: "Maori"},
{key:"map", value: "Austronesian (Other)"},
{key:"mar", value: "Marathi"},
{key:"mas", value: "Masai"},
{key:"may", value: "Malay"},
{key:"mdf", value: "Moksha"},
{key:"mdr", value: "Mandar"},
{key:"men", value: "Mende"},
{key:"mga", value: "Irish, Middle (900-1200)"},
{key:"mic", value: "Mi'kmaq; Micmac"},
{key:"min", value: "Minangkabau"},
{key:"mis", value: "Miscellaneous languages"},
{key:"mac", value: "Macedonian"},
{key:"mkd", value: "Macedonian"},
{key:"mkh", value: "Mon-Khmer (Other)"},
{key:"mlg", value: "Malagasy"},
{key:"mlt", value: "Maltese"},
{key:"mnc", value: "Manchu"},
{key:"mni", value: "Manipuri"},
{key:"mno", value: "Manobo languages"},
{key:"moh", value: "Mohawk"},
{key:"mol", value: "Moldavian"},
{key:"mon", value: "Mongolian"},
{key:"mos", value: "Mossi"},
{key:"mri", value: "Maori"},
{key:"mao", value: "Maori"},
{key:"may", value: "Malay"},
{key:"msa", value: "Malay"},
{key:"mul", value: "Multiple languages"},
{key:"mun", value: "Munda languages"},
{key:"mus", value: "Creek"},
{key:"mwl", value: "Mirandese"},
{key:"mwr", value: "Marwari"},
{key:"bur", value: "Burmese"},
{key:"mya", value: "Burmese"},
{key:"myn", value: "Mayan languages"},
{key:"myv", value: "Erzya"},
{key:"nah", value: "Nahuatl"},
{key:"nai", value: "North American Indian"},
{key:"nap", value: "Neapolitan"},
{key:"nau", value: "Nauru"},
{key:"nav", value: "Navajo; Navaho"},
{key:"nbl", value: "Ndebele, South; South Ndebele"},
{key:"nde", value: "Ndebele, North; North Ndebele"},
{key:"ndo", value: "Ndonga"},
{key:"nds", value: "Low German; Low Saxon; German, Low; Saxon, Low"},
{key:"nep", value: "Nepali"},
{key:"new", value: "Nepal Bhasa; Newari"},
{key:"nia", value: "Nias"},
{key:"nic", value: "Niger-Kordofanian (Other)"},
{key:"niu", value: "Niuean"},
{key:"dut", value: "Dutch; Flemish"},
{key:"nld", value: "Dutch; Flemish"},
{key:"nno", value: "Norwegian Nynorsk; Nynorsk, Norwegian"},
{key:"nob", value: "Bokmål, Norwegian; Norwegian Bokmål"},
{key:"nog", value: "Nogai"},
{key:"non", value: "Norse, Old"},
{key:"nor", value: "Norwegian"},
{key:"nqo", value: "N'Ko"},
{key:"nso", value: "Pedi; Sepedi; Northern Sotho"},
{key:"nub", value: "Nubian languages"},
{key:"nwc", value: "Classical Newari; Old Newari; Classical Nepal Bhasa"},
{key:"nya", value: "Chichewa; Chewa; Nyanja"},
{key:"nym", value: "Nyamwezi"},
{key:"nyn", value: "Nyankole"},
{key:"nyo", value: "Nyoro"},
{key:"nzi", value: "Nzima"},
{key:"oci", value: "Occitan (post 1500); Provençal"},
{key:"oji", value: "Ojibwa"},
{key:"ori", value: "Oriya"},
{key:"orm", value: "Oromo"},
{key:"osa", value: "Osage"},
{key:"oss", value: "Ossetian; Ossetic"},
{key:"ota", value: "Turkish, Ottoman (1500-1928)"},
{key:"oto", value: "Otomian languages"},
{key:"paa", value: "Papuan (Other)"},
{key:"pag", value: "Pangasinan"},
{key:"pal", value: "Pahlavi"},
{key:"pam", value: "Pampanga"},
{key:"pan", value: "Panjabi; Punjabi"},
{key:"pap", value: "Papiamento"},
{key:"pau", value: "Palauan"},
{key:"peo", value: "Persian, Old (ca.600-400 B.C.)"},
{key:"per", value: "Persian"},
{key:"phi", value: "Philippine (Other)"},
{key:"phn", value: "Phoenician"},
{key:"pli", value: "Pali"},
{key:"pol", value: "Polish"},
{key:"pon", value: "Pohnpeian"},
{key:"por", value: "Portuguese"},
{key:"pra", value: "Prakrit languages"},
{key:"pro", value: "Provençal, Old (to 1500)"},
{key:"pus", value: "Pushto"},
{key:"que", value: "Quechua"},
{key:"raj", value: "Rajasthani"},
{key:"rap", value: "Rapanui"},
{key:"rar", value: "Rarotongan"},
{key:"roa", value: "Romance (Other)"},
{key:"roh", value: "Raeto-Romance"},
{key:"rom", value: "Romany"},
{key:"ron", value: "Romanian"},
{key:"rum", value: "Romanian"},
{key:"run", value: "Rundi"},
{key:"rup", value: "Aromanian; Arumanian; Macedo-Romanian"},
{key:"rus", value: "Russian"},
{key:"sad", value: "Sandawe"},
{key:"sag", value: "Sango"},
{key:"sah", value: "Yakut"},
{key:"sai", value: "South American Indian (Other)"},
{key:"sal", value: "Salishan languages"},
{key:"sam", value: "Samaritan Aramaic"},
{key:"san", value: "Sanskrit"},
{key:"sas", value: "Sasak"},
{key:"sat", value: "Santali"},
{key:"scc", value: "Serbian"},
{key:"scn", value: "Sicilian"},
{key:"sco", value: "Scots"},
{key:"scr", value: "Croatian"},
{key:"sel", value: "Selkup"},
{key:"sem", value: "Semitic (Other)"},
{key:"sga", value: "Irish, Old (to 900)"},
{key:"sgn", value: "Sign Languages"},
{key:"shn", value: "Shan"},
{key:"sid", value: "Sidamo"},
{key:"sin", value: "Sinhala; Sinhalese"},
{key:"sio", value: "Siouan languages"},
{key:"sit", value: "Sino-Tibetan (Other)"},
{key:"sla", value: "Slavic (Other)"},
{key:"slo", value: "Slovak"},
{key:"slk", value: "Slovak"},
{key:"slv", value: "Slovenian"},
{key:"sma", value: "Southern Sami"},
{key:"sme", value: "Northern Sami"},
{key:"smi", value: "Sami languages (Other)"},
{key:"smj", value: "Lule Sami"},
{key:"smn", value: "Inari Sami"},
{key:"smo", value: "Samoan"},
{key:"sms", value: "Skolt Sami"},
{key:"sna", value: "Shona"},
{key:"snd", value: "Sindhi"},
{key:"snk", value: "Soninke"},
{key:"sog", value: "Sogdian"},
{key:"som", value: "Somali"},
{key:"son", value: "Songhai"},
{key:"sot", value: "Sotho, Southern"},
{key:"spa", value: "Spanish; Castilian"},
{key:"sqi", value: "Albanian"},
{key:"alb", value: "Albanian"},
{key:"srd", value: "Sardinian"},
{key:"srn", value: "Sranan Togo"},
{key:"scc", value: "Serbian"},
{key:"srp", value: "Serbian"},
{key:"srr", value: "Serer"},
{key:"ssa", value: "Nilo-Saharan (Other)"},
{key:"ssw", value: "Swati"},
{key:"suk", value: "Sukuma"},
{key:"sun", value: "Sundanese"},
{key:"sus", value: "Susu"},
{key:"sux", value: "Sumerian"},
{key:"swa", value: "Swahili"},
{key:"swe", value: "Swedish"},
{key:"syr", value: "Syriac"},
{key:"tah", value: "Tahitian"},
{key:"tai", value: "Tai (Other)"},
{key:"tam", value: "Tamil"},
{key:"tat", value: "Tatar"},
{key:"tel", value: "Telugu"},
{key:"tem", value: "Timne"},
{key:"ter", value: "Tereno"},
{key:"tet", value: "Tetum"},
{key:"tgk", value: "Tajik"},
{key:"tgl", value: "Tagalog"},
{key:"tha", value: "Thai"},
{key:"tib", value: "Tibetan"},
{key:"tig", value: "Tigre"},
{key:"tir", value: "Tigrinya"},
{key:"tiv", value: "Tiv"},
{key:"tkl", value: "Tokelau"},
{key:"tlh", value: "Klingon; tlhIngan-Hol"},
{key:"tli", value: "Tlingit"},
{key:"tmh", value: "Tamashek"},
{key:"tog", value: "Tonga (Nyasa)"},
{key:"ton", value: "Tonga (Tonga Islands)"},
{key:"tpi", value: "Tok Pisin"},
{key:"tsi", value: "Tsimshian"},
{key:"tsn", value: "Tswana"},
{key:"tso", value: "Tsonga"},
{key:"tuk", value: "Turkmen"},
{key:"tum", value: "Tumbuka"},
{key:"tup", value: "Tupi languages"},
{key:"tur", value: "Turkish"},
{key:"tut", value: "Altaic (Other)"},
{key:"tvl", value: "Tuvalu"},
{key:"twi", value: "Twi"},
{key:"tyv", value: "Tuvinian"},
{key:"udm", value: "Udmurt"},
{key:"uga", value: "Ugaritic"},
{key:"uig", value: "Uighur; Uyghur"},
{key:"ukr", value: "Ukrainian"},
{key:"umb", value: "Umbundu"},
{key:"und", value: "Undetermined"},
{key:"urd", value: "Urdu"},
{key:"uzb", value: "Uzbek"},
{key:"vai", value: "Vai"},
{key:"ven", value: "Venda"},
{key:"vie", value: "Vietnamese"},
{key:"vol", value: "Volapük"},
{key:"vot", value: "Votic"},
{key:"wak", value: "Wakashan languages"},
{key:"wal", value: "Walamo"},
{key:"war", value: "Waray"},
{key:"was", value: "Washo"},
{key:"wel", value: "Welsh"},
{key:"wen", value: "Sorbian languages"},
{key:"wln", value: "Walloon"},
{key:"wol", value: "Wolof"},
{key:"xal", value: "Kalmyk; Oirat"},
{key:"xho", value: "Xhosa"},
{key:"yao", value: "Yao"},
{key:"yap", value: "Yapese"},
{key:"yid", value: "Yiddish"},
{key:"yor", value: "Yoruba"},
{key:"ypk", value: "Yupik languages"},
{key:"zap", value: "Zapotec"},
{key:"zen", value: "Zenaga"},
{key:"zha", value: "Zhuang; Chuang"},
{key:"zho", value: "Chinese"},
{key:"chi", value: "Chinese"},
{key:"znd", value: "Zande"},
{key:"zul", value: "Zulu"},
{key:"zun", value: "Zuni"},
{key:"zxx", value: "No linguistic content"},
{key:"zza", value: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"}
];
