<%@ page language="java" contentType="text/html; charset=UTF-8"  pageEncoding="UTF-8"%>
<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ page import="com.arcsoft.web4transcoder.AppConfig" %>

<script type="text/javascript">
var license = new Object();
license.PRODUCT = "PRODUCT";
license.PRODUCT_HEADER = "PRODUCT_HEADER";
license.PRODUCT_TYPE = "PRODUCT_TYPE";
license.PRODUCT_SHOWING_SPEED = "PRODUCT_SHOWING_SPEED";
license.PRODUCT_QUICK_TRANSCODING = "PRODUCT_QUICK_TRANSCODING";
license.PRODUCT_LIVE_BACKUP = "PRODUCT_LIVE_BACKUP";

license.ENCODINGPOLICY_BEST = "ENCODINGPOLICY_BEST";
license.ENCODINGPOLICY_GOOD = "ENCODINGPOLICY_GOOD";
license.ENCODINGPOLICY_BALANCE = "ENCODINGPOLICY_BALANCE";
license.ENCODINGPOLICY_FAST = "ENCODINGPOLICY_FAST";
license.ENCODINGPOLICY_FASTEST = "ENCODINGPOLICY_FASTEST";
license.ENCODINGPOLICY_CUSTOM = "ENCODINGPOLICY_CUSTOM";
license.ENCODINGPOLICY = "ENCODINGPOLICY";
license.PRIORITY = "PRIORITY";
license.POST_PROCESS = "POST_PROCESS";
license.TRANS_GPU_ID = "TRANS_GPU_ID";
license.TRANS_VIDEO_DECODING = "TRANS_VIDEO_DECODING";
license.FILL_ON_STREAM_LOST = "FILL_ON_STREAM_LOST";

license.INPUT_FILE = "INPUT_FILE";
license.INPUT_OSS = "INPUT_OSS";
license.INPUT_COMBINATION = "INPUT_COMBINATION";
license.INPUT_BD = "INPUT_BD";
license.INPUT_DVD = "INPUT_DVD";
license.INPUT_P2 = "INPUT_P2";
license.INPUT_DISC_MULTITITLES = "INPUT_DISC_MULTITITLES";
license.INPUT_SIGNAL_BACKUP = "INPUT_SIGNAL_BACKUP";

license.INPUT_NETWORK = "INPUT_NETWORK";
license.INPUT_CABLE = "INPUT_CABLE";
license.INPUT_NETWORK_TSOVERUDP = "INPUT_NETWORK_TSOVERUDP";
license.INPUT_NETWORK_TSOVERUDP_BACKUP = "INPUT_NETWORK_TSOVERUDP_BACKUP";
license.INPUT_NETWORK_ESOVERRTP = "INPUT_NETWORK_ESOVERRTP";
license.INPUT_NETWORK_ESOVERRTP_BACKUP = "INPUT_NETWORK_ESOVERRTP_BACKUP";
license.INPUT_NETWORK_MMS = "INPUT_NETWORK_MMS";
license.INPUT_NETWORK_FTP = "INPUT_NETWORK_FTP";
license.INPUT_NETWORK_HTTP = "INPUT_NETWORK_HTTP";
license.INPUT_NETWORK_HTTP_BACKUP = "INPUT_NETWORK_HTTP_BACKUP";
license.INPUT_NETWORK_RTSP = "INPUT_NETWORK_RTSP";
license.INPUT_NETWORK_RTSP_BACKUP = "INPUT_NETWORK_RTSP_BACKUP";
license.INPUT_NETWORK_RTMP = "INPUT_NETWORK_RTMP";
license.INPUT_NETWORK_RTMP_BACKUP = "INPUT_NETWORK_RTMP_BACKUP";
license.INPUT_CABLE_HDSDI = "INPUT_CABLE_HDSDI";
license.INPUT_CANDIDATE_SDI = "INPUT_CANDIDATE_SDI";
license.INPUT_SDI_MULTI_AUDIO = "INPUT_SDI_MULTI_AUDIO";
license.INPUT_SDI_4K = "INPUT_SDI_4K";
license.INPUT_CABLE_CVBS = "INPUT_CABLE_CVBS";
license.INPUT_CABLE_HDMI = "INPUT_CABLE_HDMI";
license.INPUT_CABLE_AES_EBU = "INPUT_CABLE_AES_EBU";
license.INPUT_CABLE_ASI = "INPUT_CABLE_ASI";
license.INPUT_PREVIEW = "INPUT_PREVIEW";
license.INPUT_EDITING = "INPUT_EDITING";
license.INPUT_PREVIEW_ASI = "INPUT_PREVIEW_ASI";
license.INPUT_PREVIEW_SDI = "INPUT_PREVIEW_SDI";
license.INPUT_ALLOW_PROGRAM_ID_CHANGE = "INPUT_ALLOW_PROGRAM_ID_CHANGE";
license.INPUT_LIVE_SYNC_MODE = "INPUT_LIVE_SYNC_MODE";
license.INPUT_DELAY_OUTPUT_TIME = "INPUT_DELAY_OUTPUT_TIME";
license.INPUT_FILL_TYPE="INPUT_FILL_TYPE";
license.INPUT_FILL_MODE_LOST="INPUT_FILL_MODE_LOST";
license.INPUT_FAILOVER_TIME = "INPUT_FAILOVER_TIME";
license.INPUT_AUDIO_CHANNEL = "INPUT_AUDIO_CHANNEL";

license.OUTPUT_FILE_3GP = "OUTPUT_FILE_3GP";
license.OUTPUT_FILE_TS = "OUTPUT_FILE_TS";
license.OUTPUT_FILE_AVI = "OUTPUT_FILE_AVI";
license.OUTPUT_FILE_PS = "OUTPUT_FILE_PS";
license.OUTPUT_FILE_MKV = "OUTPUT_FILE_MKV";
license.OUTPUT_FILE_MXF = "OUTPUT_FILE_MXF";
license.OUTPUT_FILE_MP4 = "OUTPUT_FILE_MP4";	
license.OUTPUT_FILE_FLV = "OUTPUT_FILE_FLV";	
license.OUTPUT_FILE_MOV = "OUTPUT_FILE_MOV";
license.OUTPUT_FILE_ASF = "OUTPUT_FILE_ASF";
license.OUTPUT_FILE_HLS = "OUTPUT_FILE_HLS";
license.OUTPUT_FILE_AAC = "OUTPUT_FILE_AAC";
license.OUTPUT_FILE_MP3 = "OUTPUT_FILE_MP3";
license.OUTPUT_FILE_WMA = "OUTPUT_FILE_WMA";
license.OUTPUT_FILE_MP2 = "OUTPUT_FILE_MP2";
license.OUTPUT_FILE_AMR = "OUTPUT_FILE_AMR";
license.OUTPUT_FILE_AC3 = "OUTPUT_FILE_AC3";
license.OUTPUT_FILE_OGG = "OUTPUT_FILE_OGG";
license.OUTPUT_FILE_WAV = "OUTPUT_FILE_WAV";
license.OUTPUT_FILE_MSSMOOTHSTREAMING = "OUTPUT_FILE_MSSMOOTHSTREAMING";
license.OUTPUT_STREAM_TSOVERUDP = "OUTPUT_STREAM_TSOVERUDP";
license.OUTPUT_STREAM_TSOVERRTP = "OUTPUT_STREAM_TSOVERRTP";
license.OUTPUT_STREAM_ESOVERRTP = "OUTPUT_STREAM_ESOVERRTP";
license.OUTPUT_STREAM_RTSP = "OUTPUT_STREAM_RTSP";
license.OUTPUT_STREAM_RTMP = "OUTPUT_STREAM_RTMP";
license.OUTPUT_STREAM_HLS = "OUTPUT_STREAM_HLS";
license.OUTPUT_STREAM_HDS = "OUTPUT_STREAM_HDS";	
license.OUTPUT_STREAM_MSSMOOTHSTREAMING = "OUTPUT_STREAM_MSSMOOTHSTREAMING";
license.OUTPUT_STREAM_FLVOVERHTTP = "OUTPUT_STREAM_FLVOVERHTTP";
license.OUTPUT_STREAM_MP3OVERHTTP = "OUTPUT_STREAM_MP3OVERHTTP";
license.OUTPUT_STREAM_TSOVERHTTP = "OUTPUT_STREAM_TSOVERHTTP";
license.OUTPUT_STREAM_ASISTREAMING = "OUTPUT_STREAM_ASISTREAMING";
license.OUTPUT_STREAM_SDISTREAMING = "OUTPUT_STREAM_SDISTREAMING";

license.OUTPUT_PREVIEW = "OUTPUT_PREVIEW";
license.OUTPUT_PREVIEW_LIVE = "OUTPUT_PREVIEW_LIVE";
license.OUTPUT_SIM_HD = "OUTPUT_SIM_HD";
license.OUTPUT_SIM_HD_SCENE = "OUTPUT_SIM_HD_SCENE";
license.OUTPUT_FILE_SEGMENT_TYPE = "OUTPUT_FILE_SEGMENT_TYPE";
license.OUTPUT_HLS_PLAYLIST_NAME_MODE = "OUTPUT_HLS_PLAYLIST_NAME_MODE";
license.OUTPUT_HLS_DELETE_UPLOADED = "OUTPUT_HLS_DELETE_UPLOADED";
license.OUTPUT_HLS_IFRAME_PLAYLIST = "OUTPUT_HLS_IFRAME_PLAYLIST";
license.OUTPUT_HLS_ENCRYPTION = "OUTPUT_HLS_ENCRYPTION";
license.OUTPUT_HLS_DISTRIBUTE_LOCAL = "OUTPUT_HLS_DISTRIBUTE_LOCAL";
license.OUTPUT_HLS_DISTRIBUTE_POINT = "OUTPUT_HLS_DISTRIBUTE_POINT";
license.OUTPUT_HLS_VOD_LIST = "OUTPUT_HLS_VOD_LIST";

license.AUTOMATION_WATCHFOLDER = "AUTOMATION_WATCHFOLDER";
license.AUTOMATION_WATCHFOLDER_FTP = "AUTOMATION_WATCHFOLDER_FTP";
license.AUTOMATION_WATCHFOLDER_SUBFOLDER = "AUTOMATION_WATCHFOLDER_SUBFOLDER";
license.WATCHFOLDER_SUBTITLE = "WATCHFOLDER_SUBTITLE";
license.AUTOMATION_SCHEDULE = "AUTOMATION_SCHEDULE";

license.IMAGE_EDITING_ANTISHAKING = "IMAGE_EDITING_ANTISHAKING";
license.IMAGE_EDITING_ANTISHAKING_DELAY = "IMAGE_EDITING_ANTISHAKING_DELAY";
license.IMAGE_EDITING_DELIGHT = "IMAGE_EDITING_DELIGHT";
license.IMAGE_EDITING_DENOISE = "IMAGE_EDITING_DENOISE";
license.IMAGE_EDITING_DENOISE_QUALITY = "IMAGE_EDITING_DENOISE_QUALITY";
license.IMAGE_EDITING_DEINTERLACE = "IMAGE_EDITING_DEINTERLACE";
license.IMAGE_EDITING_DEBLOCK = "IMAGE_EDITING_DEBLOCK";
license.IMAGE_EDITING_SHARPEN = "IMAGE_EDITING_SHARPEN";
license.IMAGE_EDITING_ANTIALIAS = "IMAGE_EDITING_ANTIALIAS";
license.IMAGE_EDITING_BRIGHT = "IMAGE_EDITING_BRIGHT";
license.IMAGE_EDITING_CONTRAST = "IMAGE_EDITING_CONTRAST";
license.IMAGE_EDITING_SATURATION = "IMAGE_EDITING_SATURATION";
license.IMAGE_EDITING_HUE = "IMAGE_EDITING_HUE";
license.IMAGE_EDITING_RESIZEALG = "IMAGE_EDITING_RESIZEALG";
license.IMAGE_EDITING_DEINTERLACEALG = "IMAGE_EDITING_DEINTERLACEALG";
license.IMAGE_EDITING_ROTATION = "IMAGE_EDITING_ROTATION";

license.VIDEO_EDITING = "VIDEO_EDITING";
license.VIDEO_EDITING_MOSAIC_INSERTION = "VIDEO_EDITING_MOSAIC_INSERTION";
license.VIDEO_EDITING_MOSAIC_TIME = "VIDEO_EDITING_MOSAIC_TIME";
license.VIDEO_EDITING_CROPPING = "VIDEO_EDITING_CROPPING";
license.VIDEO_EDITING_PADDING_IMAGE = "VIDEO_EDITING_PADDING_IMAGE";
license.VIDEO_EDITING_AUDIO_DELAY = "VIDEO_EDITING_AUDIO_DELAY";
license.VIDEO_EDITING_TIMELINE_CUT_TRIM = "VIDEO_EDITING_TIMELINE_CUT_TRIM";
license.VIDEO_EDITING_ADS = "VIDEO_EDITING_ADS";

license.VIDEO_EDITING_LOGO_INSERTION = "VIDEO_EDITING_LOGO_INSERTION";
license.VIDEO_EDITING_PIP_INSERTION = "VIDEO_EDITING_PIP_INSERTION";
license.VIDEO_EDITING_IMAGE_GRABBING = "VIDEO_EDITING_IMAGE_GRABBING";
license.VIDEO_EDITING_IMAGE_GRABBING_NORMAL = "VIDEO_EDITING_IMAGE_GRABBING_NORMAL";
license.VIDEO_EDITING_IMAGE_GRABBING_SKIP_COUNT = "VIDEO_EDITING_IMAGE_GRABBING_SKIP_COUNT";
license.VIDEO_EDITING_IMAGE_GRABBING_SKIP_INTERVAL = "VIDEO_EDITING_IMAGE_GRABBING_SKIP_INTERVAL";
license.VIDEO_EDITING_MOTION_ICON = "VIDEO_EDITING_MOTION_ICON";
license.VIDEO_EDITING_DYNAMIC_TEXT = "VIDEO_EDITING_DYNAMIC_TEXT";
license.VIDEO_EDITING_WATERMARKING_INSERTION = "VIDEO_EDITING_WATERMARKING_INSERTION";
license.VIDEO_EDITING_LIVE_SETTING = "VIDEO_EDITING_LIVE_SETTING";
license.VIDEO_EDITING_SRT_EXTERNAL_SUBTITILE_INSERTION = "VIDEO_EDITING_SRT_EXTERNAL_SUBTITILE_INSERTION";
license.VIDEO_EDITING_SSA_EXTERNAL_SUBTITILE_INSERTION = "VIDEO_EDITING_SSA_EXTERNAL_SUBTITILE_INSERTION";
license.VIDEO_EDITING_ASS_EXTERNAL_SUBTITILE_INSERTION = "VIDEO_EDITING_ASS_EXTERNAL_SUBTITILE_INSERTION";

license.VIDEO_ENCODER_PASSTHROUGH = "VIDEO_ENCODER_PASSTHROUGH";
license.VIDEO_ENCODER_H264 = "VIDEO_ENCODER_H264";
license.VIDEO_ENCODER_H264_AVCINTRA50 = "VIDEO_ENCODER_H264_AVCINTRA50";
license.VIDEO_ENCODER_H264_AVCINTRA100 = "VIDEO_ENCODER_H264_AVCINTRA100";
license.VIDEO_ENCODER_H264_AVCINTRA200 = "VIDEO_ENCODER_H264_AVCINTRA200";
license.VIDEO_ENCODER_MPEG2 = "VIDEO_ENCODER_MPEG2";
license.VIDEO_ENCODER_MPEG2_HIGH422 = "VIDEO_ENCODER_MPEG2_HIGH422";
license.VIDEO_ENCODER_MPEG2_MPEG30 = "VIDEO_ENCODER_MPEG2_MPEG30";
license.VIDEO_ENCODER_MPEG2_MPEG40 = "VIDEO_ENCODER_MPEG2_MPEG40";
license.VIDEO_ENCODER_MPEG2_MPEG50 = "VIDEO_ENCODER_MPEG2_MPEG50";
license.VIDEO_ENCODER_H263 = "VIDEO_ENCODER_H263";
license.VIDEO_ENCODER_H263_LEVEL = "VIDEO_ENCODER_H263_LEVEL";
license.VIDEO_ENCODER_DV = "VIDEO_ENCODER_DV";
license.VIDEO_ENCODER_S263 = "VIDEO_ENCODER_S263";
license.VIDEO_ENCODER_WMV9 = "VIDEO_ENCODER_WMV9";
license.VIDEO_ENCODER_MPEG1 = "VIDEO_ENCODER_MPEG1";
license.VIDEO_ENCODER_MPEG4 = "VIDEO_ENCODER_MPEG4";
license.VIDEO_ENCODER_AVS = "VIDEO_ENCODER_AVS";
license.VIDEO_ENCODER_AVSP = "VIDEO_ENCODER_AVSP";
license.VIDEO_ENCODER_H265 = "VIDEO_ENCODER_H265";
license.VIDEO_ENCODER_PRORES = "VIDEO_ENCODER_PRORES";
license.VIDEO_ENCODER_RAW = "VIDEO_ENCODER_RAW";
license.VIDEO_ENCODER_DNXHD = "VIDEO_ENCODER_DNXHD";
license.VIDEO_ENCODER_INTERLACE_FIELD_1ST_MODE_SHOW = "VIDEO_ENCODER_INTERLACE_FIELD_1ST_MODE_SHOW";
license.VIDEO_ENCODER_TWO_PASS = "VIDEO_ENCODER_TWO_PASS";
license.VIDEO_ENCODER_CQ = "VIDEO_ENCODER_CQ";
license.VIDEO_ENCODER_CRF = "VIDEO_ENCODER_CRF";

license.VIDEO_ENCODER_SMARTBORDER = "VIDEO_ENCODER_SMARTBORDER";
license.VIDEO_ENCODER_BORDER_FIT_WIDTH = "VIDEO_ENCODER_BORDER_FIT_WIDTH";
license.VIDEO_ENCODER_BORDER_FIT_HEIGHT = "VIDEO_ENCODER_BORDER_FIT_HEIGHT";
license.VIDEO_ENCODER_INTERLACE_MBAFF = "VIDEO_ENCODER_INTERLACE_MBAFF";
license.VIDEO_ENCODER_INTERLACE_PAFF = "VIDEO_ENCODER_INTERLACE_PAFF";
license.VIDEO_ENCODER_QUALITY_LEVEL_HARD = "VIDEO_ENCODER_QUALITY_LEVEL_HARD";
license.VIDEO_ENCODER_CODEC_ID = "VIDEO_ENCODER_CODEC_ID";
license.VIDEO_ENCODER_PLAY_RATE = "VIDEO_ENCODER_PLAY_RATE";
license.VIDEO_ENCODER_GOP_MODE_ID = "VIDEO_ENCODER_GOP_MODE_ID";
license.VIDEO_ENCODER_GOP_TYPE = "VIDEO_ENCODER_GOP_TYPE";
license.VIDEO_ENCODER_FRAME_RATE_MODE = "VIDEO_ENCODER_FRAME_RATE_MODE";
license.VIDEO_ENCODER_INTERPOLATE = "VIDEO_ENCODER_INTERPOLATE";
license.VIDEO_ENCODER_QUALITY_LEVEL_X265 = "VIDEO_ENCODER_QUALITY_LEVEL_X265";
license.VIDEO_ENCODER_BIT_DEPTH = "VIDEO_ENCODER_BIT_DEPTH";
license.VIDEO_FILL_ON_VIDEO_LOST = "VIDEO_FILL_ON_VIDEO_LOST";

license.AUDIO_ENCODER_PASSTHROUGH = "AUDIO_ENCODER_PASSTHROUGH";
license.AUDIO_ENCODER_AAC = "AUDIO_ENCODER_AAC";	
license.AUDIO_ENCODER_MP2 = "AUDIO_ENCODER_MP2";
license.AUDIO_ENCODER_MP3 = "AUDIO_ENCODER_MP3";
license.AUDIO_ENCODER_WMA = "AUDIO_ENCODER_WMA";
license.AUDIO_ENCODER_AMR = "AUDIO_ENCODER_AMR";
license.AUDIO_ENCODER_AC3 = "AUDIO_ENCODER_AC3";
license.AUDIO_ENCODER_DTS = "AUDIO_ENCODER_DTS";
license.AUDIO_ENCODER_VORBIS = "AUDIO_ENCODER_VORBIS";
license.AUDIO_ENCODER_PCM = "AUDIO_ENCODER_PCM";
license.AUDIO_ENCODER_DDP = "AUDIO_ENCODER_DDP";

license.AUDIO_CHANNEL_1 = "AUDIO_CHANNEL_1";
license.AUDIO_CHANNEL_2 = "AUDIO_CHANNEL_2";
license.AUDIO_CHANNEL_51 = "AUDIO_CHANNEL_51";
license.AUDIO_CHANNEL_71 = "AUDIO_CHANNEL_71";

license.AUDIO_VOLUME_MODE = "AUDIO_VOLUME_MODE";
license.AUDIO_VOLUME_BOOST = "AUDIO_VOLUME_BOOST";
license.AUDIO_VOLUME_BALANCE = "AUDIO_VOLUME_BALANCE";
license.AUDIO_LRCHANNEL_PROCESS = "AUDIO_LRCHANNEL_PROCESS";
license.AUDIO_ENCODER_CODEC_ID = "AUDIO_ENCODER_CODEC_ID";
license.AUDIO_ENCODER_PLAY_RATE = "AUDIO_ENCODER_PLAY_RATE";
license.AUDIO_DENOISE = "AUDIO_DENOISE";
license.AUDIO_MULTIPLE_INPUT = "AUDIO_MULTIPLE_INPUT";
license.AUDIO_FILL_ON_AUDIO_LOST = "AUDIO_FILL_ON_AUDIO_LOST";

license.EMERGENCY_PLAYBACK = "EMERGENCY_PLAYBACK";
license.TIANYUDRM = "TIANYUDRM";
license.ARCDRM = "ARCDRM";
license.TS_MUXER_ADVANCE_OPTION = "TS_MUXER_ADVANCE_OPTION";
license.OUTPUT_CANDIDATE_LOCATION = "OUTPUT_CANDIDATE_LOCATION";

license.ETH_SMART_SELECTION = "ETH_SMART_SELECTION";
license.ALERT_EMAIL = "ALERT_EMAIL";
license.UPLOADING_FTP = "UPLOADING_FTP";
license.UPLOADING_HTTP_HLS = "UPLOADING_HTTP_HLS";

license.LIVE_RUNTIME_PREVIEW = "LIVE_RUNTIME_PREVIEW";
license.LIVE_RUNTIME_SEEK = "LIVE_RUNTIME_SEEK";
license.LIVE_RUNTIME_PAUSE = "LIVE_RUNTIME_PAUSE";
license.MATERIAL_MANAGEMENT = "MATERIAL_MANAGEMENT";

license.THROUGHTPUT_1_IN_N_OUT = "THROUGHTPUT_1_IN_N_OUT";
license.THROUGHTPUT_TASK_COUNT = "THROUGHTPUT_TASK_COUNT";
license.THROUGHTPUT_HDOUTPUT_COUNT = "THROUGHTPUT_HDOUTPUT_COUNT";
license.THROUGHTPUT_SDOUTPUT_COUNT = "THROUGHTPUT_SDOUTPUT_COUNT";

license.ADS_ENLIGHT = "ADS_ENLIGHT";
license.WATCHFOLDER_TYPE_TEDA = "WATCHFOLDER_TYPE_TEDA";

license.CORE = "CORE";
license.LIVE = "LIVE";
license.MAL = "MAL";
license.ENABLED = "1";
license.DISABLED = "0";
license.PRODUCT_TYPE_SINGLE = "0";
license.PRODUCT_TYPE_LIVE = "1";
license.PRODUCT_TYPE_CLOUD = "2";
license.PRODUCT_TYPE_MAL = "3";

//extend defination
license.EX_VIDEO_EDITING_EXTERNAL_SUBTITLE = "EX_VIDEO_EDITING_EXTERNAL_SUBTITLE";
license.EX_OUTPUT_FILE = "EX_OUTPUT_FILE";
license.EX_OUTPUT_APPLE_STREAMING = "EX_OUTPUT_APPLE_STREAMING";
license.EX_OUTPUT_FLASH_STREAMING = "EX_OUTPUT_FLASH_STREAMING";
license.EX_OUTPUT_UDP_STREAMING = "EX_OUTPUT_UDP_STREAMING";
license.EX_OUTPUT_RTP_STREAMING = "EX_OUTPUT_RTP_STREAMING";
license.EX_OUTPUT_HTTP_STREAMING = "EX_OUTPUT_HTTP_STREAMING";
license.EX_OUTPUT_MS_SMOOTH_STREAMING = "EX_OUTPUT_MS_SMOOTH_STREAMING";
license.EX_OUTPUT_ASI_STREAMING = "EX_OUTPUT_ASI_STREAMING";
license.EX_OUTPUT_SDI_STREAMING = "EX_OUTPUT_SDI_STREAMING";
license.EX_DRM = "EX_DRM";

var g_LicenseData = [
{key: license.ENABLED, value: "1"},
{key: license.DISABLED, value: "0"},
<s:iterator value="[0].limitationMap" var="key">
{key: "<s:property value='key'/>" , value: "<s:property value='value'/>"},
</s:iterator>
{key: "END", value: "END"}
];

function GetLicense(key) {
	var value = null;
	
	//value = GetLicenseSpecial(key);
	//if(value != null) return value;
	
	value = uGetMapValue(g_LicenseData, key);
	if(value != null) return value;
	
	value = GetLicenseCompose(key);
	
	return value;
}

/* can delete this function */
function GetLicenseSpecial(key) {
	var value = null;
	if(key == license.AUDIO_ENCODER_AAC) {
		var haveAudioCodec = false;
		for(var i = 0; i < g_LicenseData.length; i++) {
			var pilot = g_LicenseData[i].key;
			if(pilot == license.AUDIO_ENCODER_AAC
				|| pilot == license.AUDIO_ENCODER_MP2
				|| pilot == license.AUDIO_ENCODER_MP3
				|| pilot == license.AUDIO_ENCODER_WMA
				|| pilot == license.AUDIO_ENCODER_AMR
				|| pilot == license.AUDIO_ENCODER_AC3
				|| pilot == license.AUDIO_ENCODER_DTS
				|| pilot == license.AUDIO_ENCODER_PCM
				|| pilot == license.AUDIO_ENCODER_DDP) {
				if(g_LicenseData[i].value == license.ENABLED) {
					haveAudioCodec = true;
					break;
				}
			}
		}
		
		if(!haveAudioCodec) {
			value = license.ENABLED;
		}
	}
	return value;
}

function GetLicenseCompose(key) {
	var value = null;
	
	if(key == license.EX_VIDEO_EDITING_EXTERNAL_SUBTITLE) {
		if(uGetMapValue(g_LicenseData, license.VIDEO_EDITING_SRT_EXTERNAL_SUBTITILE_INSERTION) == license.ENABLED 
				|| uGetMapValue(g_LicenseData, license.VIDEO_EDITING_SSA_EXTERNAL_SUBTITILE_INSERTION) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	} else if(key == license.EX_OUTPUT_FILE) {
		if(uGetMapValue(g_LicenseData, license.OUTPUT_FILE_TS) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_3GP) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_AVI) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_PS) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_MKV) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_MXF) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_MP4) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_FLV) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_MOV) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_ASF) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_HLS) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.OUTPUT_FILE_MSSMOOTHSTREAMING) == license.ENABLED
				) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	} else if(key == license.EX_OUTPUT_APPLE_STREAMING) {
		if(uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_HLS) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	} else if(key == license.EX_OUTPUT_FLASH_STREAMING) {
		if(uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_RTMP) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	} else if(key == license.EX_OUTPUT_UDP_STREAMING) {
		if(uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_TSOVERUDP) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	} else if(key == license.EX_OUTPUT_RTP_STREAMING) {
		if(uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_ESOVERRTP) == license.ENABLED 
				|| uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_TSOVERRTP) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	} else if(key == license.EX_OUTPUT_HTTP_STREAMING) {
		if(uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_FLVOVERHTTP) == license.ENABLED 
				|| uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_TSOVERHTTP) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	} else if(key == license.EX_OUTPUT_MS_SMOOTH_STREAMING) {
		if(uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_MSSMOOTHSTREAMING) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	}
	else if(key == license.EX_OUTPUT_ASI_STREAMING) {
		if(uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_ASISTREAMING) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	}
	else if(key == license.EX_OUTPUT_SDI_STREAMING) {
		if(uGetMapValue(g_LicenseData, license.OUTPUT_STREAM_SDISTREAMING) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	}
	else if(key == license.EX_DRM) {
		if(uGetMapValue(g_LicenseData, license.TIANYUDRM) == license.ENABLED
				|| uGetMapValue(g_LicenseData, license.ARCDRM) == license.ENABLED) {
			value = license.ENABLED;
		} else {
			value = license.DISABLED;
		}
	}
	
	return value;
}

</script>