var cpjs = {
	TaskId : ".TaskId",
	ContentPackaging : ".ContentPackaging",
	PreviewTrigger : ".PreviewTrigger",
	PositionTrigger : ".PositionTrigger",
	ApplyTrigger : ".ApplyTrigger",
	ContentTabList : "#ContentTabList",
	ContentTabIndex : ".ContentTabIndex",
	ContentTabLabel : ".ContentTabLabel",
	ContentParamItem : ".ContentParamItem",
	OutputGroupSelect : "#OutputGroupSelect",
	OutputSelect : "#OutputSelect",
	SwitchTaskTrigger : ".SwitchTaskTrigger",
	TabCheck : ".TabCheck",
	DefaultButton : ".DefaultButton",
	SelectedTab : ".SelectedTab",
	ContentPackagingId : ".ContentPackagingId",
	ContentPackagingOperate : ".ContentPackagingOperate",
	NewMotionIconTrigger : ".NewMotionIconTrigger",
	NewDynamicTextTrigger : ".NewDynamicTextTrigger",
	DeleteProcessorTrigger : ".DeleteProcessorTrigger",
	BackTrigger : ".BackTrigger",
	SaveTrigger : ".SaveTrigger",
	ContentPackagingName : ".ContentPackagingName",
	ContentPackagingDescription : ".ContentPackagingDescription",
	SelectSourceTrigger : ".SelectSourceTrigger",
	PlayTrigger : ".PlayTrigger",
	ContentPackagingSource : ".ContentPackagingSource",
	OutputWidth : ".OutputWidth",
	OutputHeight : ".OutputHeight",
	AspectRatioX : ".AspectRatioX",
	AspectRatioY : ".AspectRatioY",
	FromUri : ".FromUri",
	ResolutionTrigger : ".ResolutionTrigger",
	AspectRatioTrigger : ".AspectRatioTrigger",
	cplItemCheckBox : ".cplItemCheckBox",
	cplItemId : ".cplItemId",
	ContentPackagingList : ".ContentPackagingList",
	cplItemType : ".cplItemType",
	cplItemName : ".cplItemName",
	cplHeadCheckBox : ".cplHeadCheckBox",
	cplItemCheckBox : ".cplItemCheckBox",
	ImportTrigger : ".ImportTrigger",
	InputSource : ".InputSource",
	CopySourceTrigger : ".CopySourceTrigger",
	CopyOutputTrigger : ".CopyOutputTrigger",
	PlaySourceTrigger : ".PlaySourceTrigger",
	PlayOutputTrigger : ".PlayOutputTrigger",
	UploadMaterialTrigger : ".UploadMaterialTrigger",
	ContentPackagingMgrTrigger : ".ContentPackagingMgrTrigger",
	DynamicTextLabel : ".DynamicTextLabel",
	cpl_dynamictext : ".cpl_dynamictext",
	_end : ""
};

var cptmpl = {
	ContentTab : "#TemplateLib #ContentTab",
	ContentMotionIcon : "#TemplateLib #ContentMotionIcon",
	ContentDynamicText : "#TemplateLib #ContentDynamicText",
	ContentPackagingListHead : "#TemplateLib .ContentPackagingListHead",
	ContentPackagingListItem : "#TemplateLib .ContentPackagingListItem",
	_end : ""
};
